/**
 * E2E Test Infrastructure Setup
 *
 * Orchestrates the full setup sequence:
 * 1. Start Docker containers (anvil, anvil1, localterra)
 * 2. Wait for health checks
 * 3. Deploy EVM contracts to anvil and anvil1
 * 4. Deploy Terra bridge contract to localterra
 * 5. Configure bridges (register chains on each other)
 * 6. Deploy TokenA/B/C on all 3 chains
 * 7. Register all tokens across all bridges
 * 8. Write contract addresses to .env.e2e.local
 *
 * Used as globalSetup for both Vitest integration and Playwright E2E tests.
 */

import { execSync } from 'child_process'
import { writeFileSync } from 'fs'
import { resolve } from 'path'
import { waitForAllChains, areAllChainsHealthy } from './health'
import { deployEvmContracts } from './deploy-evm'
import { deployTerraBridge } from './deploy-terra'
import { deployAllTokens } from './deploy-tokens'
import { registerAllTokens } from './register-tokens'

const ROOT_DIR = resolve(__dirname, '../../../../..')
const ENV_FILE = resolve(ROOT_DIR, '.env.e2e.local')

export default async function setup(): Promise<void> {
  console.log('=== E2E Test Infrastructure Setup ===\n')
  const start = Date.now()

  try {
    // 1. Start Docker containers (skip if already healthy)
    const alreadyRunning = await areAllChainsHealthy()
    if (alreadyRunning) {
      console.log('[setup] All chains already running, skipping docker compose up')
    } else {
      console.log('[setup] Starting Docker containers...')
      execSync('docker compose up -d anvil anvil1 localterra', {
        cwd: ROOT_DIR,
        stdio: 'inherit',
      })
    }

    // 2. Wait for health checks
    await waitForAllChains(90_000) // 90s timeout for cold start

    // 3. Deploy EVM contracts to both Anvil chains
    console.log('\n[setup] Deploying EVM contracts...')
    const anvilContracts = deployEvmContracts('http://localhost:8545')
    const anvil1Contracts = deployEvmContracts('http://localhost:8546')

    // 4. Deploy Terra bridge contract
    console.log('\n[setup] Deploying Terra bridge...')
    const terraBridgeAddress = deployTerraBridge()

    // 5-6. Deploy tokens and register across bridges
    console.log('\n[setup] Deploying tokens across all chains...')
    const tokenAddresses = deployAllTokens(terraBridgeAddress)

    // 7. Register tokens across all bridges
    console.log('\n[setup] Registering tokens across bridges...')
    registerAllTokens(
      {
        anvil: {
          bridge: anvilContracts.bridgeAddress,
          tokenRegistry: anvilContracts.tokenRegistryAddress,
          lockUnlock: anvilContracts.lockUnlockAddress,
          chainRegistry: anvilContracts.chainRegistryAddress,
        },
        anvil1: {
          bridge: anvil1Contracts.bridgeAddress,
          tokenRegistry: anvil1Contracts.tokenRegistryAddress,
          lockUnlock: anvil1Contracts.lockUnlockAddress,
          chainRegistry: anvil1Contracts.chainRegistryAddress,
        },
        terra: terraBridgeAddress,
      },
      tokenAddresses
    )

    // 8. Write environment file
    const envContent = [
      '# Auto-generated by E2E setup - do not edit',
      `# Generated at ${new Date().toISOString()}`,
      '',
      '# Anvil (chain 31337)',
      `VITE_EVM_BRIDGE_ADDRESS=${anvilContracts.bridgeAddress}`,
      `VITE_EVM_ROUTER_ADDRESS=${anvilContracts.bridgeAddress}`,
      `EVM_ACCESS_MANAGER_ADDRESS=${anvilContracts.accessManagerAddress}`,
      `EVM_CHAIN_REGISTRY_ADDRESS=${anvilContracts.chainRegistryAddress}`,
      `EVM_TOKEN_REGISTRY_ADDRESS=${anvilContracts.tokenRegistryAddress}`,
      `EVM_LOCK_UNLOCK_ADDRESS=${anvilContracts.lockUnlockAddress}`,
      `EVM_MINT_BURN_ADDRESS=${anvilContracts.mintBurnAddress}`,
      '',
      '# Anvil1 (chain 31338)',
      `VITE_EVM1_BRIDGE_ADDRESS=${anvil1Contracts.bridgeAddress}`,
      `EVM1_ACCESS_MANAGER_ADDRESS=${anvil1Contracts.accessManagerAddress}`,
      `EVM1_CHAIN_REGISTRY_ADDRESS=${anvil1Contracts.chainRegistryAddress}`,
      `EVM1_TOKEN_REGISTRY_ADDRESS=${anvil1Contracts.tokenRegistryAddress}`,
      `EVM1_LOCK_UNLOCK_ADDRESS=${anvil1Contracts.lockUnlockAddress}`,
      `EVM1_MINT_BURN_ADDRESS=${anvil1Contracts.mintBurnAddress}`,
      '',
      '# Terra (localterra)',
      `VITE_TERRA_BRIDGE_ADDRESS=${terraBridgeAddress}`,
      '',
      '# Tokens on Anvil',
      `ANVIL_TOKEN_A=${tokenAddresses.anvil.tokenA}`,
      `ANVIL_TOKEN_B=${tokenAddresses.anvil.tokenB}`,
      `ANVIL_TOKEN_C=${tokenAddresses.anvil.tokenC}`,
      '',
      '# Tokens on Anvil1',
      `ANVIL1_TOKEN_A=${tokenAddresses.anvil1.tokenA}`,
      `ANVIL1_TOKEN_B=${tokenAddresses.anvil1.tokenB}`,
      `ANVIL1_TOKEN_C=${tokenAddresses.anvil1.tokenC}`,
      '',
      '# Tokens on Terra',
      `TERRA_TOKEN_A=${tokenAddresses.terra.tokenA}`,
      `TERRA_TOKEN_B=${tokenAddresses.terra.tokenB}`,
      `TERRA_TOKEN_C=${tokenAddresses.terra.tokenC}`,
      '',
      '# Network',
      'VITE_NETWORK=local',
      '',
    ].join('\n')

    writeFileSync(ENV_FILE, envContent, 'utf8')
    console.log(`\n[setup] Environment written to ${ENV_FILE}`)

    const elapsed = ((Date.now() - start) / 1000).toFixed(1)
    console.log(`\n=== E2E Setup Complete (${elapsed}s) ===\n`)
  } catch (error) {
    console.error('\n[setup] Setup failed:', error)
    throw error
  }
}

// Allow running directly: npx tsx src/test/e2e-infra/setup.ts
if (require.main === module) {
  setup().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
