/**
 * E2E Test Infrastructure Setup
 *
 * Orchestrates the full setup sequence:
 * 1. Start Docker containers (anvil, anvil1, localterra, postgres)
 * 2. Wait for health checks
 * 3. Deploy EVM contracts to anvil and anvil1
 * 4. Deploy Terra bridge contract to localterra
 * 5. Configure bridges (register chains on each other)
 * 6. Deploy TokenA/B/C on all 3 chains
 * 7. Register all tokens across all bridges
 * 8. Write contract addresses to .env.e2e.local
 * 9. Start operator and canceler
 *
 * Used as globalSetup for both Vitest integration and Playwright E2E tests.
 */

import { execSync } from 'child_process'
import { writeFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { waitForAllChains, areAllChainsHealthy } from './health'
import { loadE2eEnvFile } from '../../utils/loadE2eEnvFile'
import { deployEvmContracts, fundLockUnlock, setCancelWindow, addCancelerEvm } from './deploy-evm'
import { deployTerraBridge, addCancelerTerra } from './deploy-terra'
import { deployAllTokens, KDEC_DECIMALS } from './deploy-tokens'
import { registerAllTokens } from './register-tokens'
import { isPlaceholderAddress } from './deploy-terra'
import { startOperator } from './operator'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT_DIR = resolve(__dirname, '../../../../..')
const FRONTEND_DIR = resolve(__dirname, '../../..')
const ENV_FILE = resolve(ROOT_DIR, '.env.e2e.local')
/** Committed localnet program id (packages/contracts-solana/Anchor.toml [programs.localnet]). */
const LOCALNET_SOLANA_BRIDGE_PROGRAM_ID = 'mYwQnKWjsX86Tmr2muoj19QtL1gmfX4iq5jZjCdG8Tb'
// Vite reads .env.local from the project root (packages/frontend/).
// We write VITE_* vars here so import.meta.env picks them up at dev time.
const VITE_ENV_FILE = resolve(FRONTEND_DIR, '.env.local')

/**
 * Start the canceler via canceler-ctl.sh (which sources .env.e2e.local automatically).
 * Builds the binary first if needed, then starts instance 1.
 */
function startCanceler(rootDir: string): void {
  // Build canceler (release) if binary doesn't exist
  const cancelerBinary = resolve(rootDir, 'packages/canceler/target/release/cl8y-canceler')
  if (!existsSync(cancelerBinary)) {
    console.log('[setup] Building canceler (release)...')
    execSync('cargo build --manifest-path packages/canceler/Cargo.toml --release', {
      cwd: rootDir,
      stdio: 'inherit',
      timeout: 300_000,
    })
  }

  try {
    execSync('./scripts/canceler-ctl.sh start', {
      cwd: rootDir,
      stdio: 'inherit',
      timeout: 30_000,
    })
  } catch (err) {
    console.warn('[setup] Warning: canceler start failed:', (err as Error).message?.slice(0, 200))
  }
}

export default async function setup(): Promise<void> {
  console.log('=== E2E Test Infrastructure Setup ===\n')
  const start = Date.now()

  try {
    // Match Terra LCD/RPC from .env.e2e.local / process.env before health checks — avoids false "down" + full redeploy.
    loadE2eEnvFile(ENV_FILE)

    // Skip full re-deployment if .env.e2e.local already exists and chains are healthy
    const alreadyRunning = await areAllChainsHealthy()
    if (alreadyRunning && existsSync(ENV_FILE)) {
      console.log('[setup] All chains already running and .env.e2e.local exists, skipping deployment')
      // Ensure Vite env file exists (may have been cleaned by a previous teardown)
      if (!existsSync(VITE_ENV_FILE)) {
        const { readFileSync } = await import('fs')
        const envLines = readFileSync(ENV_FILE, 'utf8').split('\n')
        const viteLines = envLines.filter((l: string) => l.startsWith('VITE_'))
        if (!viteLines.some((l) => l.startsWith('VITE_SOLANA_PROGRAM_ID='))) {
          viteLines.push(`VITE_SOLANA_PROGRAM_ID=${LOCALNET_SOLANA_BRIDGE_PROGRAM_ID}`)
        }
        writeFileSync(VITE_ENV_FILE, [
          '# Auto-generated by E2E setup for Vite - do not edit',
          ...viteLines,
          '',
        ].join('\n'), 'utf8')
        console.log(`[setup] Vite env re-created from ${ENV_FILE}`)
      }
      console.log('[setup] Ensuring operator is running...')
      await startOperator(ENV_FILE)
      console.log('[setup] Ensuring canceler is running...')
      startCanceler(ROOT_DIR)
      const elapsed = ((Date.now() - start) / 1000).toFixed(1)
      console.log(`\n=== E2E Setup Complete (reused, ${elapsed}s) ===\n`)
      return
    }

    // 1. Start Docker containers (skip if already healthy)
    if (alreadyRunning) {
      console.log('[setup] All chains already running, skipping docker compose up')
    } else {
      console.log('[setup] Starting Docker containers...')
      execSync('docker compose up -d anvil anvil1 localterra postgres solana', {
        cwd: ROOT_DIR,
        stdio: 'inherit',
        env: { ...process.env },
      })
    }

    // 2. Wait for health checks
    await waitForAllChains(90_000) // 90s timeout for cold start

    // 2b. Fund deployer + deploy Solana bridge program (validator is fresh each compose up)
    console.log('\n[setup] Funding Solana deployer (airdrop)...')
    try {
      execSync('bash scripts/solana/airdrop-for-anchor-deploy.sh', {
        cwd: ROOT_DIR,
        stdio: 'inherit',
        env: { ...process.env, SOLANA_RPC_URL: 'http://127.0.0.1:8899' },
        timeout: 120_000,
      })
    } catch (err) {
      console.warn('[setup] Solana airdrop script failed:', (err as Error).message?.slice(0, 200))
    }
    console.log('\n[setup] Deploying Solana programs (Anchor)...')
    try {
      execSync('bash scripts/solana/anchor-deploy-localnet.sh', {
        cwd: ROOT_DIR,
        stdio: 'inherit',
        timeout: 600_000,
      })
    } catch (err) {
      console.warn(
        '[setup] Solana Anchor deploy failed (Solana E2E may be incomplete):',
        (err as Error).message?.slice(0, 300)
      )
    }

    // 3. Deploy EVM contracts to both Anvil chains
    //    V2 chain IDs are globally unique: anvil=1, terra=2, anvil1=3
    console.log('\n[setup] Deploying EVM contracts...')
    const anvilContracts = deployEvmContracts('http://localhost:8545', 1, 'evm_31337')
    const anvil1Contracts = deployEvmContracts('http://localhost:8546', 3, 'evm_31338')

    // 4. Deploy Terra bridge contract
    console.log('\n[setup] Deploying Terra bridge...')
    const terraBridgeAddress = deployTerraBridge()

    // 5-6. Deploy tokens and register across bridges
    console.log('\n[setup] Deploying tokens across all chains...')
    const tokenAddresses = await deployAllTokens(terraBridgeAddress)

    // 7. Register tokens across all bridges
    console.log('\n[setup] Registering tokens across bridges...')
    registerAllTokens(
      {
        anvil: {
          bridge: anvilContracts.bridgeAddress,
          tokenRegistry: anvilContracts.tokenRegistryAddress,
          lockUnlock: anvilContracts.lockUnlockAddress,
          chainRegistry: anvilContracts.chainRegistryAddress,
        },
        anvil1: {
          bridge: anvil1Contracts.bridgeAddress,
          tokenRegistry: anvil1Contracts.tokenRegistryAddress,
          lockUnlock: anvil1Contracts.lockUnlockAddress,
          chainRegistry: anvil1Contracts.chainRegistryAddress,
        },
        terra: terraBridgeAddress,
      },
      tokenAddresses,
      {
        evmRpcUrl: process.env.EVM_RPC_URL || 'http://localhost:8545',
        evm1RpcUrl: process.env.EVM1_RPC_URL || 'http://localhost:8546',
      }
    )

    // 8. Fund LockUnlock contracts with test tokens for cross-chain withdrawals.
    //    Each chain's LockUnlock must hold tokens to unlock them when withdrawals
    //    are executed on that chain (destination side of a cross-chain transfer).
    console.log('\n[setup] Funding LockUnlock contracts with test tokens...')
    const FUND_AMOUNT = '500000000000000000000000' // 500k tokens (18 decimals)
    const FUND_AMOUNT_LUNC = '500000000000' // 500k LUNC (6 decimals)
    const kdecFundAmounts: Record<string, string> = {
      anvil: (500_000n * 10n ** BigInt(KDEC_DECIMALS.anvil)).toString(),
      anvil1: (500_000n * 10n ** BigInt(KDEC_DECIMALS.anvil1)).toString(),
    }
    for (const [chain, rpc, lockUnlock, tokens] of [
      ['anvil', 'http://localhost:8545', anvilContracts.lockUnlockAddress, tokenAddresses.anvil],
      ['anvil1', 'http://localhost:8546', anvil1Contracts.lockUnlockAddress, tokenAddresses.anvil1],
    ] as const) {
      for (const [name, addr] of [['tokenA', tokens.tokenA], ['tokenB', tokens.tokenB], ['tokenC', tokens.tokenC]] as const) {
        try {
          fundLockUnlock(rpc, lockUnlock, addr, FUND_AMOUNT)
          console.log(`[setup] Funded ${chain} LockUnlock with ${name}`)
        } catch (err) {
          console.warn(`[setup] Warning: failed to fund ${chain} LockUnlock with ${name}:`, err)
        }
      }
      try {
        fundLockUnlock(rpc, lockUnlock, tokens.lunc, FUND_AMOUNT_LUNC)
        console.log(`[setup] Funded ${chain} LockUnlock with LUNC`)
      } catch (err) {
        console.warn(`[setup] Warning: failed to fund ${chain} LockUnlock with LUNC:`, err)
      }
      try {
        fundLockUnlock(rpc, lockUnlock, tokens.kdec, kdecFundAmounts[chain])
        console.log(`[setup] Funded ${chain} LockUnlock with KDEC`)
      } catch (err) {
        console.warn(`[setup] Warning: failed to fund ${chain} LockUnlock with KDEC:`, err)
      }
      try {
        fundLockUnlock(rpc, lockUnlock, tokens.sol, (500_000n * 10n ** 9n).toString())
        console.log(`[setup] Funded ${chain} LockUnlock with SOL`)
      } catch (err) {
        console.warn(`[setup] Warning: failed to fund ${chain} LockUnlock with SOL:`, err)
      }
    }

    // 9. Set cancel window to minimum (15s) for fast test execution.
    //    Default is 5 minutes which would make tests wait too long.
    //    The operator tracks cancel window with wall-clock time, so this
    //    ensures withdrawals auto-execute within ~15 real seconds.
    console.log('\n[setup] Configuring cancel window...')
    setCancelWindow('http://localhost:8545', anvilContracts.bridgeAddress, 15)
    setCancelWindow('http://localhost:8546', anvil1Contracts.bridgeAddress, 15)

    // 10. Register canceler on all bridges (canceler uses its own wallet per canceler .env)
    console.log('\n[setup] Registering canceler on bridges...')
    try {
      addCancelerEvm('http://localhost:8545', anvilContracts.bridgeAddress)
      addCancelerEvm('http://localhost:8546', anvil1Contracts.bridgeAddress)
      addCancelerTerra(terraBridgeAddress)
    } catch (err) {
      console.warn('[setup] Warning: failed to add canceler:', (err as Error).message)
    }

    // 11. Write environment file
    const envContent = [
      '# Auto-generated by E2E setup - do not edit',
      `# Generated at ${new Date().toISOString()}`,
      '',
      '# Anvil (chain 31337)',
      `VITE_EVM_BRIDGE_ADDRESS=${anvilContracts.bridgeAddress}`,
      `VITE_EVM_ROUTER_ADDRESS=${anvilContracts.bridgeAddress}`,
      `EVM_ACCESS_MANAGER_ADDRESS=${anvilContracts.accessManagerAddress}`,
      `EVM_CHAIN_REGISTRY_ADDRESS=${anvilContracts.chainRegistryAddress}`,
      `EVM_TOKEN_REGISTRY_ADDRESS=${anvilContracts.tokenRegistryAddress}`,
      `EVM_LOCK_UNLOCK_ADDRESS=${anvilContracts.lockUnlockAddress}`,
      `EVM_MINT_BURN_ADDRESS=${anvilContracts.mintBurnAddress}`,
      '',
      '# Anvil1 (chain 31338)',
      `VITE_EVM1_BRIDGE_ADDRESS=${anvil1Contracts.bridgeAddress}`,
      `EVM1_ACCESS_MANAGER_ADDRESS=${anvil1Contracts.accessManagerAddress}`,
      `EVM1_CHAIN_REGISTRY_ADDRESS=${anvil1Contracts.chainRegistryAddress}`,
      `EVM1_TOKEN_REGISTRY_ADDRESS=${anvil1Contracts.tokenRegistryAddress}`,
      `EVM1_LOCK_UNLOCK_ADDRESS=${anvil1Contracts.lockUnlockAddress}`,
      `EVM1_MINT_BURN_ADDRESS=${anvil1Contracts.mintBurnAddress}`,
      '',
      '# Terra (localterra)',
      `VITE_TERRA_BRIDGE_ADDRESS=${terraBridgeAddress}`,
      '',
      '# Tokens on Anvil',
      `ANVIL_TOKEN_A=${tokenAddresses.anvil.tokenA}`,
      `ANVIL_TOKEN_B=${tokenAddresses.anvil.tokenB}`,
      `ANVIL_TOKEN_C=${tokenAddresses.anvil.tokenC}`,
      `ANVIL_LUNC=${tokenAddresses.anvil.lunc}`,
      `ANVIL_KDEC=${tokenAddresses.anvil.kdec}`,
      `ANVIL_SOL=${tokenAddresses.anvil.sol}`,
      `ANVIL_T2022=${tokenAddresses.anvil.t2022}`,
      '',
      '# Tokens on Anvil1',
      `ANVIL1_TOKEN_A=${tokenAddresses.anvil1.tokenA}`,
      `ANVIL1_TOKEN_B=${tokenAddresses.anvil1.tokenB}`,
      `ANVIL1_TOKEN_C=${tokenAddresses.anvil1.tokenC}`,
      `ANVIL1_LUNC=${tokenAddresses.anvil1.lunc}`,
      `ANVIL1_KDEC=${tokenAddresses.anvil1.kdec}`,
      `ANVIL1_SOL=${tokenAddresses.anvil1.sol}`,
      `ANVIL1_T2022=${tokenAddresses.anvil1.t2022}`,
      '',
      '# Tokens on Terra (empty = CW20 not deployed, use uluna for EVM<->Terra)',
      `TERRA_TOKEN_A=${isPlaceholderAddress(tokenAddresses.terra.tokenA) ? '' : tokenAddresses.terra.tokenA}`,
      `TERRA_TOKEN_B=${isPlaceholderAddress(tokenAddresses.terra.tokenB) ? '' : tokenAddresses.terra.tokenB}`,
      `TERRA_TOKEN_C=${isPlaceholderAddress(tokenAddresses.terra.tokenC) ? '' : tokenAddresses.terra.tokenC}`,
      `TERRA_KDEC=${isPlaceholderAddress(tokenAddresses.terra.kdec) ? '' : tokenAddresses.terra.kdec}`,
      `TERRA_SOL=${isPlaceholderAddress(tokenAddresses.terra.sol) ? '' : tokenAddresses.terra.sol}`,
      `TERRA_T2022=${isPlaceholderAddress(tokenAddresses.terra.t2022) ? '' : tokenAddresses.terra.t2022}`,
      '',
      '# SPL mints (QA — same logical tokens as EVM/Terra)',
      `SOLANA_TOKEN_A=${tokenAddresses.solana.tokenA}`,
      `SOLANA_TOKEN_B=${tokenAddresses.solana.tokenB}`,
      `SOLANA_TOKEN_C=${tokenAddresses.solana.tokenC}`,
      `SOLANA_LUNC=${tokenAddresses.solana.lunc}`,
      `SOLANA_KDEC=${tokenAddresses.solana.kdec}`,
      `SOLANA_WSOL=${tokenAddresses.solana.wsol}`,
      `SOLANA_T2022=${tokenAddresses.solana.t2022}`,
      '',
      '# Network',
      'VITE_NETWORK=local',
      'VITE_POLLING_INTERVAL=5000',
      '',
      '# Terra LCD/RPC (host ports — must match docker compose E2E_TERRA_* and health.ts)',
      `TERRA_LCD_URL=${process.env.TERRA_LCD_URL || `http://127.0.0.1:${process.env.E2E_TERRA_LCD_PORT || '1317'}`}`,
      `TERRA_RPC_URL=${process.env.TERRA_RPC_URL || `http://127.0.0.1:${process.env.E2E_TERRA_RPC_PORT || '26657'}`}`,
      `VITE_TERRA_LCD_URL=${process.env.VITE_TERRA_LCD_URL || process.env.TERRA_LCD_URL || `http://127.0.0.1:${process.env.E2E_TERRA_LCD_PORT || '1317'}`}`,
      `VITE_TERRA_RPC_URL=${process.env.VITE_TERRA_RPC_URL || process.env.TERRA_RPC_URL || `http://127.0.0.1:${process.env.E2E_TERRA_RPC_PORT || '26657'}`}`,
      '',
      '# Solana local RPC + program id (chain selector + SPL registration)',
      'VITE_SOLANA_RPC_URL=http://127.0.0.1:8899',
      `VITE_SOLANA_PROGRAM_ID=${LOCALNET_SOLANA_BRIDGE_PROGRAM_ID}`,
      '',
    ].join('\n')

    writeFileSync(ENV_FILE, envContent, 'utf8')
    console.log(`\n[setup] Environment written to ${ENV_FILE}`)

    // Also write VITE_* vars to packages/frontend/.env.local so Vite picks them up.
    // Vite only reads .env, .env.local, .env.[mode], .env.[mode].local from its project root.
    const _terraLcd =
      process.env.TERRA_LCD_URL || `http://127.0.0.1:${process.env.E2E_TERRA_LCD_PORT || '1317'}`
    const _terraRpc =
      process.env.TERRA_RPC_URL || `http://127.0.0.1:${process.env.E2E_TERRA_RPC_PORT || '26657'}`
    const viteEnvContent = [
      '# Auto-generated by E2E setup for Vite - do not edit',
      `# Generated at ${new Date().toISOString()}`,
      '',
      `VITE_NETWORK=local`,
      'VITE_POLLING_INTERVAL=5000',
      `VITE_TERRA_LCD_URL=${_terraLcd}`,
      `VITE_TERRA_RPC_URL=${_terraRpc}`,
      `VITE_EVM_BRIDGE_ADDRESS=${anvilContracts.bridgeAddress}`,
      `VITE_EVM_ROUTER_ADDRESS=${anvilContracts.bridgeAddress}`,
      `VITE_EVM1_BRIDGE_ADDRESS=${anvil1Contracts.bridgeAddress}`,
      `VITE_TERRA_BRIDGE_ADDRESS=${terraBridgeAddress}`,
      `VITE_LOCK_UNLOCK_ADDRESS=${anvilContracts.lockUnlockAddress}`,
      `VITE_BRIDGE_TOKEN_ADDRESS=${tokenAddresses.anvil.lunc}`,
      '',
      '# Local Solana (docker compose solana service + anchor deploy in setup)',
      'VITE_SOLANA_RPC_URL=http://127.0.0.1:8899',
      `VITE_SOLANA_PROGRAM_ID=${LOCALNET_SOLANA_BRIDGE_PROGRAM_ID}`,
      '',
    ].join('\n')
    writeFileSync(VITE_ENV_FILE, viteEnvContent, 'utf8')
    console.log(`[setup] Vite env written to ${VITE_ENV_FILE}`)

    // 12. Start operator (force restart to pick up new contract addresses)
    console.log('\n[setup] Starting operator...')
    await startOperator(ENV_FILE, true)

    // 13. Start canceler
    console.log('\n[setup] Starting canceler...')
    startCanceler(ROOT_DIR)

    const elapsed = ((Date.now() - start) / 1000).toFixed(1)
    console.log(`\n=== E2E Setup Complete (${elapsed}s) ===\n`)
  } catch (error) {
    console.error('\n[setup] Setup failed:', error)
    throw error
  }
}

// Allow running directly: npx tsx src/test/e2e-infra/setup.ts
const isMain = process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/^\//, ''))
  || process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  setup().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
