/**
 * E2E Test Infrastructure Setup
 *
 * Orchestrates the full setup sequence:
 * 1. Start Docker containers (anvil, anvil1, localterra)
 * 2. Wait for health checks
 * 3. Deploy EVM contracts to anvil and anvil1
 * 4. Deploy Terra bridge contract to localterra
 * 5. Configure bridges (register chains on each other)
 * 6. Deploy TokenA/B/C on all 3 chains
 * 7. Register all tokens across all bridges
 * 8. Write contract addresses to .env.e2e.local
 *
 * Used as globalSetup for both Vitest integration and Playwright E2E tests.
 */

import { execSync } from 'child_process'
import { writeFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { waitForAllChains, areAllChainsHealthy } from './health'
import { deployEvmContracts, fundLockUnlock, setCancelWindow, addCancelerEvm } from './deploy-evm'
import { deployTerraBridge, addCancelerTerra } from './deploy-terra'
import { deployAllTokens } from './deploy-tokens'
import { registerAllTokens } from './register-tokens'
import { isPlaceholderAddress } from './deploy-terra'
import { startOperator } from './operator'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT_DIR = resolve(__dirname, '../../../../..')
const FRONTEND_DIR = resolve(__dirname, '../../..')
const ENV_FILE = resolve(ROOT_DIR, '.env.e2e.local')
// Vite reads .env.local from the project root (packages/frontend/).
// We write VITE_* vars here so import.meta.env picks them up at dev time.
const VITE_ENV_FILE = resolve(FRONTEND_DIR, '.env.local')

export default async function setup(): Promise<void> {
  console.log('=== E2E Test Infrastructure Setup ===\n')
  const start = Date.now()

  try {
    // Skip full re-deployment if .env.e2e.local already exists and chains are healthy
    const alreadyRunning = await areAllChainsHealthy()
    if (alreadyRunning && existsSync(ENV_FILE)) {
      console.log('[setup] All chains already running and .env.e2e.local exists, skipping deployment')
      // Ensure Vite env file exists (may have been cleaned by a previous teardown)
      if (!existsSync(VITE_ENV_FILE)) {
        const { readFileSync } = await import('fs')
        const envLines = readFileSync(ENV_FILE, 'utf8').split('\n')
        const viteLines = envLines.filter((l: string) => l.startsWith('VITE_'))
        writeFileSync(VITE_ENV_FILE, [
          '# Auto-generated by E2E setup for Vite - do not edit',
          ...viteLines,
          '',
        ].join('\n'), 'utf8')
        console.log(`[setup] Vite env re-created from ${ENV_FILE}`)
      }
      console.log('[setup] Ensuring operator is running...')
      await startOperator(ENV_FILE)
      const elapsed = ((Date.now() - start) / 1000).toFixed(1)
      console.log(`\n=== E2E Setup Complete (reused, ${elapsed}s) ===\n`)
      return
    }

    // 1. Start Docker containers (skip if already healthy)
    if (alreadyRunning) {
      console.log('[setup] All chains already running, skipping docker compose up')
    } else {
      console.log('[setup] Starting Docker containers...')
      execSync('docker compose up -d anvil anvil1 localterra', {
        cwd: ROOT_DIR,
        stdio: 'inherit',
      })
    }

    // 2. Wait for health checks
    await waitForAllChains(90_000) // 90s timeout for cold start

    // 3. Deploy EVM contracts to both Anvil chains
    //    V2 chain IDs are globally unique: anvil=1, terra=2, anvil1=3
    console.log('\n[setup] Deploying EVM contracts...')
    const anvilContracts = deployEvmContracts('http://localhost:8545', 1, 'evm_31337')
    const anvil1Contracts = deployEvmContracts('http://localhost:8546', 3, 'evm_31338')

    // 4. Deploy Terra bridge contract
    console.log('\n[setup] Deploying Terra bridge...')
    const terraBridgeAddress = deployTerraBridge()

    // 5-6. Deploy tokens and register across bridges
    console.log('\n[setup] Deploying tokens across all chains...')
    const tokenAddresses = deployAllTokens(terraBridgeAddress)

    // 7. Register tokens across all bridges
    console.log('\n[setup] Registering tokens across bridges...')
    registerAllTokens(
      {
        anvil: {
          bridge: anvilContracts.bridgeAddress,
          tokenRegistry: anvilContracts.tokenRegistryAddress,
          lockUnlock: anvilContracts.lockUnlockAddress,
          chainRegistry: anvilContracts.chainRegistryAddress,
        },
        anvil1: {
          bridge: anvil1Contracts.bridgeAddress,
          tokenRegistry: anvil1Contracts.tokenRegistryAddress,
          lockUnlock: anvil1Contracts.lockUnlockAddress,
          chainRegistry: anvil1Contracts.chainRegistryAddress,
        },
        terra: terraBridgeAddress,
      },
      tokenAddresses
    )

    // 8. Fund LockUnlock contracts with test tokens for cross-chain withdrawals.
    //    Each chain's LockUnlock must hold tokens to unlock them when withdrawals
    //    are executed on that chain (destination side of a cross-chain transfer).
    console.log('\n[setup] Funding LockUnlock contracts with test tokens...')
    const FUND_AMOUNT = '500000000000000000000000' // 500k tokens (18 decimals)
    const FUND_AMOUNT_LUNC = '500000000000' // 500k LUNC (6 decimals)
    for (const [chain, rpc, lockUnlock, tokens] of [
      ['anvil', 'http://localhost:8545', anvilContracts.lockUnlockAddress, tokenAddresses.anvil],
      ['anvil1', 'http://localhost:8546', anvil1Contracts.lockUnlockAddress, tokenAddresses.anvil1],
    ] as const) {
      for (const [name, addr] of [['tokenA', tokens.tokenA], ['tokenB', tokens.tokenB], ['tokenC', tokens.tokenC]] as const) {
        try {
          fundLockUnlock(rpc, lockUnlock, addr, FUND_AMOUNT)
          console.log(`[setup] Funded ${chain} LockUnlock with ${name}`)
        } catch (err) {
          console.warn(`[setup] Warning: failed to fund ${chain} LockUnlock with ${name}:`, err)
        }
      }
      try {
        fundLockUnlock(rpc, lockUnlock, tokens.lunc, FUND_AMOUNT_LUNC)
        console.log(`[setup] Funded ${chain} LockUnlock with LUNC`)
      } catch (err) {
        console.warn(`[setup] Warning: failed to fund ${chain} LockUnlock with LUNC:`, err)
      }
    }

    // 9. Set cancel window to minimum (15s) for fast test execution.
    //    Default is 5 minutes which would make tests wait too long.
    //    The operator tracks cancel window with wall-clock time, so this
    //    ensures withdrawals auto-execute within ~15 real seconds.
    console.log('\n[setup] Configuring cancel window...')
    setCancelWindow('http://localhost:8545', anvilContracts.bridgeAddress, 15)
    setCancelWindow('http://localhost:8546', anvil1Contracts.bridgeAddress, 15)

    // 10. Register canceler on all bridges (canceler uses its own wallet per canceler .env)
    console.log('\n[setup] Registering canceler on bridges...')
    try {
      addCancelerEvm('http://localhost:8545', anvilContracts.bridgeAddress)
      addCancelerEvm('http://localhost:8546', anvil1Contracts.bridgeAddress)
      addCancelerTerra(terraBridgeAddress)
    } catch (err) {
      console.warn('[setup] Warning: failed to add canceler:', (err as Error).message)
    }

    // 11. Write environment file
    const envContent = [
      '# Auto-generated by E2E setup - do not edit',
      `# Generated at ${new Date().toISOString()}`,
      '',
      '# Anvil (chain 31337)',
      `VITE_EVM_BRIDGE_ADDRESS=${anvilContracts.bridgeAddress}`,
      `VITE_EVM_ROUTER_ADDRESS=${anvilContracts.bridgeAddress}`,
      `EVM_ACCESS_MANAGER_ADDRESS=${anvilContracts.accessManagerAddress}`,
      `EVM_CHAIN_REGISTRY_ADDRESS=${anvilContracts.chainRegistryAddress}`,
      `EVM_TOKEN_REGISTRY_ADDRESS=${anvilContracts.tokenRegistryAddress}`,
      `EVM_LOCK_UNLOCK_ADDRESS=${anvilContracts.lockUnlockAddress}`,
      `EVM_MINT_BURN_ADDRESS=${anvilContracts.mintBurnAddress}`,
      '',
      '# Anvil1 (chain 31338)',
      `VITE_EVM1_BRIDGE_ADDRESS=${anvil1Contracts.bridgeAddress}`,
      `EVM1_ACCESS_MANAGER_ADDRESS=${anvil1Contracts.accessManagerAddress}`,
      `EVM1_CHAIN_REGISTRY_ADDRESS=${anvil1Contracts.chainRegistryAddress}`,
      `EVM1_TOKEN_REGISTRY_ADDRESS=${anvil1Contracts.tokenRegistryAddress}`,
      `EVM1_LOCK_UNLOCK_ADDRESS=${anvil1Contracts.lockUnlockAddress}`,
      `EVM1_MINT_BURN_ADDRESS=${anvil1Contracts.mintBurnAddress}`,
      '',
      '# Terra (localterra)',
      `VITE_TERRA_BRIDGE_ADDRESS=${terraBridgeAddress}`,
      '',
      '# Tokens on Anvil',
      `ANVIL_TOKEN_A=${tokenAddresses.anvil.tokenA}`,
      `ANVIL_TOKEN_B=${tokenAddresses.anvil.tokenB}`,
      `ANVIL_TOKEN_C=${tokenAddresses.anvil.tokenC}`,
      `ANVIL_LUNC=${tokenAddresses.anvil.lunc}`,
      '',
      '# Tokens on Anvil1',
      `ANVIL1_TOKEN_A=${tokenAddresses.anvil1.tokenA}`,
      `ANVIL1_TOKEN_B=${tokenAddresses.anvil1.tokenB}`,
      `ANVIL1_TOKEN_C=${tokenAddresses.anvil1.tokenC}`,
      `ANVIL1_LUNC=${tokenAddresses.anvil1.lunc}`,
      '',
      '# Tokens on Terra (empty = CW20 not deployed, use uluna for EVM<->Terra)',
      `TERRA_TOKEN_A=${isPlaceholderAddress(tokenAddresses.terra.tokenA) ? '' : tokenAddresses.terra.tokenA}`,
      `TERRA_TOKEN_B=${isPlaceholderAddress(tokenAddresses.terra.tokenB) ? '' : tokenAddresses.terra.tokenB}`,
      `TERRA_TOKEN_C=${isPlaceholderAddress(tokenAddresses.terra.tokenC) ? '' : tokenAddresses.terra.tokenC}`,
      '',
      '# Network',
      'VITE_NETWORK=local',
      'VITE_POLLING_INTERVAL=5000',
      '',
    ].join('\n')

    writeFileSync(ENV_FILE, envContent, 'utf8')
    console.log(`\n[setup] Environment written to ${ENV_FILE}`)

    // Also write VITE_* vars to packages/frontend/.env.local so Vite picks them up.
    // Vite only reads .env, .env.local, .env.[mode], .env.[mode].local from its project root.
    const viteEnvContent = [
      '# Auto-generated by E2E setup for Vite - do not edit',
      `# Generated at ${new Date().toISOString()}`,
      '',
      `VITE_NETWORK=local`,
      'VITE_POLLING_INTERVAL=5000',
      `VITE_EVM_BRIDGE_ADDRESS=${anvilContracts.bridgeAddress}`,
      `VITE_EVM_ROUTER_ADDRESS=${anvilContracts.bridgeAddress}`,
      `VITE_EVM1_BRIDGE_ADDRESS=${anvil1Contracts.bridgeAddress}`,
      `VITE_TERRA_BRIDGE_ADDRESS=${terraBridgeAddress}`,
      `VITE_LOCK_UNLOCK_ADDRESS=${anvilContracts.lockUnlockAddress}`,
      `VITE_BRIDGE_TOKEN_ADDRESS=${tokenAddresses.anvil.lunc}`,
      '',
    ].join('\n')
    writeFileSync(VITE_ENV_FILE, viteEnvContent, 'utf8')
    console.log(`[setup] Vite env written to ${VITE_ENV_FILE}`)

    // 12. Start operator (force restart to pick up new contract addresses)
    console.log('\n[setup] Starting operator...')
    await startOperator(ENV_FILE, true)

    const elapsed = ((Date.now() - start) / 1000).toFixed(1)
    console.log(`\n=== E2E Setup Complete (${elapsed}s) ===\n`)
  } catch (error) {
    console.error('\n[setup] Setup failed:', error)
    throw error
  }
}

// Allow running directly: npx tsx src/test/e2e-infra/setup.ts
const isMain = process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/^\//, ''))
  || process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isMain) {
  setup().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
