#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
BUILD_NUM_FILE="$REPO_ROOT/packages/frontend/build-number.txt"

if [ -f "$BUILD_NUM_FILE" ]; then
  CURRENT=$(cat "$BUILD_NUM_FILE")
  echo $((CURRENT + 1)) > "$BUILD_NUM_FILE"
  git add "$BUILD_NUM_FILE"
fi
