/**
 * Terra → EVM Bridge Integration Test
 *
 * Tests the full bridge transfer lifecycle from Terra to EVM (anvil):
 * 1. Record initial ERC20 balance on anvil
 * 2. Lock tokens on Terra via terrad
 * 3. Call withdrawSubmit on anvil via cast
 * 4. Wait for operator approval
 * 5. Skip cancel window, wait for execution
 * 6. Assert recipient balance increased
 *
 * ┌─────────────────────────────────────────────────────────────────────┐
 * │  REQUIRES FULL LOCAL INFRASTRUCTURE RUNNING BEFORE EXECUTION.      │
 * │                                                                    │
 * │  You need ALL of the following:                                    │
 * │    1. Anvil        (EVM devnet)       → localhost:8545             │
 * │    2. Anvil1       (second EVM chain) → localhost:8546             │
 * │    3. LocalTerra   (Cosmos devnet)    → localhost:1317 (LCD)       │
 * │    4. PostgreSQL   (operator DB)      → localhost:5433             │
 * │    5. Operator     (cl8y-relayer)     → localhost:9092             │
 * │    6. .env.e2e.local generated by the setup script                 │
 * │                                                                    │
 * │  Quick start:                                                      │
 * │    make test-bridge-integration                                    │
 * │                                                                    │
 * │  Or manually:                                                      │
 * │    docker compose up -d anvil anvil1 localterra postgres           │
 * │    npx vitest run --config vitest.config.integration.ts            │
 * │                                                                    │
 * │  DO NOT run via `npx vitest run` — use the integration config.     │
 * └─────────────────────────────────────────────────────────────────────┘
 */

import { describe, it, expect, beforeAll } from 'vitest'
import { execSync } from 'child_process'
import { existsSync } from 'fs'
import { resolve } from 'path'
import { loadE2eEnvFile } from '../../utils/loadE2eEnvFile'
import { getErc20Balance, skipAnvilTime } from '../../../e2e/fixtures/chain-helpers'
import {
  withdrawSubmitViaCast,
  withdrawExecuteViaCast,
  pollForApproval,
  ANVIL_ACCOUNTS,
} from '../../../e2e/fixtures/transfer-helpers'
import { base64ToHex } from '../../services/hashVerification'
import type { Address, Hex } from 'viem'

const ROOT_DIR = resolve(__dirname, '../../../../..')
const ENV_FILE = resolve(ROOT_DIR, '.env.e2e.local')

const ANVIL_RPC = 'http://localhost:8545'

function loadE2eBridgeEnv(): void {
  if (!existsSync(ENV_FILE)) {
    throw new Error(
      '\n' +
      '╔══════════════════════════════════════════════════════════════════╗\n' +
      '║  BRIDGE TEST ABORTED — .env.e2e.local not found                ║\n' +
      '╠══════════════════════════════════════════════════════════════════╣\n' +
      '║  This file is generated by the E2E setup script after          ║\n' +
      '║  deploying contracts to local chains.                          ║\n' +
      '║                                                                ║\n' +
      '║  Quick start:  make test-bridge-integration                    ║\n' +
      '║  Or manually:  docker compose up -d anvil anvil1 localterra    ║\n' +
      '║  Then run:     npx vitest run --config vitest.config.integration.ts ║\n' +
      '╚══════════════════════════════════════════════════════════════════╝\n'
    )
  }
  loadE2eEnvFile(ENV_FILE)
}

function terraLcdBase(): string {
  return (
    process.env.TERRA_LCD_URL ||
    process.env.VITE_TERRA_LCD_URL ||
    'http://localhost:1317'
  ).replace(/\/$/, '')
}

/** Next outgoing nonce counter on Terra bridge (after a deposit, last deposit nonce is `n - 1`). */
async function queryTerraCurrentOutgoingNonce(
  lcd: string,
  bridge: string,
  timeoutMs = 10_000
): Promise<number | null> {
  const q = Buffer.from(JSON.stringify({ current_nonce: {} })).toString('base64')
  const url = `${lcd}/cosmwasm/wasm/v1/contract/${bridge}/smart/${encodeURIComponent(q)}`
  const start = Date.now()
  while (Date.now() - start < timeoutMs) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(10_000) })
      if (!res.ok) {
        await new Promise((r) => setTimeout(r, 500))
        continue
      }
      const parsed = (await res.json()) as { data?: string | Record<string, unknown> }
      if (parsed.data == null) {
        await new Promise((r) => setTimeout(r, 500))
        continue
      }
      const inner =
        typeof parsed.data === 'string'
          ? (JSON.parse(Buffer.from(parsed.data, 'base64').toString('utf8')) as { nonce?: string | number })
          : (parsed.data as { nonce?: string | number })
      const n = inner.nonce
      if (n != null) return typeof n === 'number' ? n : parseInt(String(n), 10)
    } catch {
      /* LCD lag */
    }
    await new Promise((r) => setTimeout(r, 500))
  }
  return null
}

/** EVM token address: Terra stores dest token as 32 bytes (left-padded ERC20). */
function destTokenBytes32ToEvmAddress(tokenBytes32: Hex): Address {
  const h = tokenBytes32.replace(/^0x/i, '')
  return (`0x${h.slice(-40)}`) as Address
}

/**
 * Full Terra deposit record for `nonce` (canonical hash + fields for EVM withdrawSubmit).
 * Must match what the operator and EVM bridge use — do not recompute the hash in TS.
 */
async function queryTerraDepositInfo(
  lcd: string,
  bridge: string,
  nonce: number,
  timeoutMs = 90_000
): Promise<{
  xchainHashId: Hex
  amount: string
  nonce: number
  srcChainBytes4: Hex
  srcAccount: Hex
  destAccount: Hex
  tokenAddress: Address
} | null> {
  const q = Buffer.from(JSON.stringify({ deposit_by_nonce: { nonce } })).toString('base64')
  const url = `${lcd}/cosmwasm/wasm/v1/contract/${bridge}/smart/${encodeURIComponent(q)}`
  const start = Date.now()
  while (Date.now() - start < timeoutMs) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(10_000) })
      if (!res.ok) {
        await new Promise((r) => setTimeout(r, 2000))
        continue
      }
      const parsed = (await res.json()) as { data?: string | Record<string, unknown> }
      if (parsed.data == null) {
        await new Promise((r) => setTimeout(r, 2000))
        continue
      }
      let inner: Record<string, unknown>
      if (typeof parsed.data === 'string') {
        inner = JSON.parse(Buffer.from(parsed.data, 'base64').toString('utf8')) as Record<string, unknown>
      } else if (typeof parsed.data === 'object') {
        inner = parsed.data as Record<string, unknown>
      } else {
        await new Promise((r) => setTimeout(r, 2000))
        continue
      }
      const xid = inner.xchain_hash_id
      const srcChain = inner.src_chain
      const srcAccount = inner.src_account
      const destAccount = inner.dest_account
      const destTok = inner.dest_token_address
      const amount = inner.amount
      const n = inner.nonce
      if (
        typeof xid !== 'string' ||
        typeof srcChain !== 'string' ||
        typeof srcAccount !== 'string' ||
        typeof destAccount !== 'string' ||
        typeof destTok !== 'string' ||
        (typeof amount !== 'string' && typeof amount !== 'number') ||
        (typeof n !== 'number' && typeof n !== 'string')
      ) {
        await new Promise((r) => setTimeout(r, 2000))
        continue
      }
      const srcBytes = Uint8Array.from(atob(srcChain), (c) => c.charCodeAt(0))
      if (srcBytes.length < 4) {
        await new Promise((r) => setTimeout(r, 2000))
        continue
      }
      const srcChainBytes4 = (`0x${Array.from(srcBytes.subarray(0, 4))
        .map((b) => b.toString(16).padStart(2, '0'))
        .join('')}`) as Hex
      const tokenBytes32 = base64ToHex(destTok)
      return {
        xchainHashId: base64ToHex(xid),
        amount: String(amount),
        nonce: typeof n === 'number' ? n : parseInt(String(n), 10),
        srcChainBytes4,
        srcAccount: base64ToHex(srcAccount),
        destAccount: base64ToHex(destAccount),
        tokenAddress: destTokenBytes32ToEvmAddress(tokenBytes32),
      }
    } catch {
      /* LCD lag */
    }
    await new Promise((r) => setTimeout(r, 2000))
  }
  return null
}

describe('Terra → EVM Bridge Transfer', () => {
  let bridgeAddress: string
  let terraBridgeAddress: string
  let tokenA: string

  beforeAll(() => {
    loadE2eBridgeEnv()
    bridgeAddress = process.env.VITE_EVM_BRIDGE_ADDRESS || ''
    terraBridgeAddress = process.env.VITE_TERRA_BRIDGE_ADDRESS || ''
    tokenA = process.env.ANVIL_TOKEN_A || process.env.VITE_ANVIL_TOKEN_A || ''

    if (!bridgeAddress || !terraBridgeAddress) {
      throw new Error('Missing bridge addresses in .env.e2e.local')
    }
  })

  it('should complete a Terra → EVM transfer with operator relay', async () => {
    // Use user4 to avoid nonce conflicts with other tests running in parallel
    const recipient = ANVIL_ACCOUNTS.user4
    const recipientKey = ANVIL_ACCOUNTS.user4Key
    // Unique gross amount per run so repeat test invocations do not replay the same Terra tx / xchain id.
    const amount = String(1_000_000 + (Date.now() % 900_000)) // uluna, >= min_bridge_amount

    // 1. Deposit on Terra via terrad using V2 deposit_native message
    // dest_chain: bytes4 of V2 chain ID 1 (Anvil) as base64
    // dest_account: bytes32 left-padded recipient address as base64
    const destChainB64 = btoa(String.fromCharCode(0, 0, 0, 1)) // V2 chain ID 1 (Anvil) as bytes4 base64
    const recipientClean = recipient.slice(2).toLowerCase()
    const destAccountBytes = new Uint8Array(32)
    for (let i = 0; i < 20; i++) {
      destAccountBytes[12 + i] = parseInt(recipientClean.slice(i * 2, i * 2 + 2), 16)
    }
    const destAccountB64 = btoa(String.fromCharCode(...destAccountBytes))

    const depositMsg = JSON.stringify({
      deposit_native: {
        dest_chain: destChainB64,
        dest_account: destAccountB64,
      },
    })

    const lcdBase = terraLcdBase()
    const nonceBefore =
      (await queryTerraCurrentOutgoingNonce(lcdBase, terraBridgeAddress, 15_000)) ?? 0
    console.log(`[test] Terra outgoing nonce before deposit: ${nonceBefore}`)

    let terraTxHash: string
    try {
      const result = execSync(
        [
          'docker compose exec -T localterra',
          'terrad tx wasm execute',
          terraBridgeAddress,
          `'${depositMsg}'`,
          `--amount ${amount}uluna`,
          '--from test1',
          '--keyring-backend test',
          '--chain-id localterra',
          '--gas auto',
          '--gas-adjustment 2.5',
          '--fees 50000000uluna',
          '-y',
          '--output json',
        ].join(' '),
        { cwd: ROOT_DIR, encoding: 'utf8', timeout: 60_000 }
      )
      const txResult = JSON.parse(result) as { txhash?: string; code?: number | string; raw_log?: string }
      if (Number(txResult.code ?? 0) !== 0) {
        throw new Error(
          `[test] Terra deposit_native rejected (code=${String(txResult.code)}): ${txResult.raw_log ?? 'no log'}`
        )
      }
      terraTxHash = txResult.txhash ?? ''
      if (!terraTxHash) throw new Error('[test] Terra broadcast returned no txhash')
      console.log(`[test] Terra deposit_native tx: ${terraTxHash}`)
    } catch (err) {
      console.error('[test] Terra deposit_native failed:', err)
      throw err
    }

    // Wait for Terra tx + wasm state (current_nonce / deposit_by_nonce) on LCD
    await new Promise((r) => setTimeout(r, 4000))

    // 3. Last deposit nonce = current outgoing counter minus one, after counter advances past pre-deposit value
    let curAfter = nonceBefore
    for (let attempt = 0; attempt < 80; attempt++) {
      const cur = await queryTerraCurrentOutgoingNonce(lcdBase, terraBridgeAddress, 12_000)
      if (cur != null && cur > nonceBefore) {
        curAfter = cur
        break
      }
      await new Promise((r) => setTimeout(r, 500))
    }
    if (curAfter <= nonceBefore) {
      throw new Error(
        `[test] Terra current_nonce did not advance after deposit (before=${nonceBefore}, after=${curAfter})`
      )
    }
    const nonce = curAfter - 1
    console.log(`[test] Deposit nonce (from current_nonce): ${nonce}`)

    // 4. Canonical deposit row from Terra (hash + every field the EVM bridge must use for withdrawSubmit).
    const depositInfo = await queryTerraDepositInfo(lcdBase, terraBridgeAddress, nonce, 90_000)
    if (!depositInfo) {
      throw new Error(`[test] deposit_by_nonce(${nonce}) missing on LCD after deposit`)
    }
    if (depositInfo.nonce !== nonce) {
      throw new Error(`[test] deposit nonce mismatch: lcd=${depositInfo.nonce} expected=${nonce}`)
    }
    if (tokenA && depositInfo.tokenAddress.toLowerCase() !== tokenA.toLowerCase()) {
      console.warn(
        `[test] ANVIL_TOKEN_A (${tokenA}) differs from Terra dest_token (${depositInfo.tokenAddress}); using on-chain mapping`
      )
    }

    const destErc20 = depositInfo.tokenAddress
    const initialBalance = await getErc20Balance(ANVIL_RPC, destErc20, recipient)
    console.log(`[test] Initial ERC20 balance (${destErc20}): ${initialBalance}`)

    // 4b. Call withdrawSubmit on anvil (args must match Terra deposit byte-for-byte)
    const wsTxHash = withdrawSubmitViaCast({
      rpcUrl: ANVIL_RPC,
      bridgeAddress,
      privateKey: recipientKey,
      srcChain: depositInfo.srcChainBytes4,
      srcAccount: depositInfo.srcAccount,
      destAccount: depositInfo.destAccount,
      token: destErc20,
      amount: depositInfo.amount,
      nonce: String(depositInfo.nonce),
    })
    console.log(`[test] WithdrawSubmit tx: ${wsTxHash}`)

    // 5. Poll for operator approval (use Terra-stored xchain id — same as EVM pending withdraw if submit matched)
    const xchainHashId = depositInfo.xchainHashId
    console.log(`[test] Xchain hash id (from Terra): ${xchainHashId}`)
    console.log('[test] Polling for operator approval...')
    const approved = await pollForApproval(ANVIL_RPC, bridgeAddress, xchainHashId, 120_000)
    console.log(`[test] Approval status: ${approved}`)

    // 6. Skip cancel window on anvil
    console.log('[test] Skipping cancel window...')
    await skipAnvilTime(ANVIL_RPC, 600) // Skip 10 minutes

    // 7. Execute withdrawal on anvil (release tokens to recipient)
    console.log('[test] Calling withdrawExecute on anvil...')
    const execTxHash = withdrawExecuteViaCast({
      rpcUrl: ANVIL_RPC,
      bridgeAddress,
      privateKey: recipientKey,
      xchainHashId,
    })
    console.log(`[test] WithdrawExecute tx: ${execTxHash}`)

    // 8. Check balance — destination ERC20 comes from Terra mapping (destErc20)
    const finalBalance = await getErc20Balance(ANVIL_RPC, destErc20, recipient)
    console.log(`[test] Final balance: ${finalBalance} (was ${initialBalance})`)
    expect(finalBalance).toBeGreaterThan(initialBalance)
  }, 240_000) // LCD + operator polling need headroom on shared LocalTerra
})
