name: Frontend Bug Report
description: Report a UI/UX bug found during manual QA or from a user report
labels: ["bug", "frontend", "needs-triage"]
body:
  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      options:
        - Desktop
        - Mobile (Android)
        - Mobile (iOS)
        - Tablet (Android)
        - Tablet (iOS)
    validations:
      required: true

  - type: input
    id: device-model
    attributes:
      label: Device Model
      description: e.g. iPhone 15 Pro, Samsung Galaxy S24, Pixel 8, MacBook Pro M3
      placeholder: iPhone 15 Pro
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS & Version
      placeholder: iOS 18.2 / Android 15 / macOS 15.2 / Ubuntu 24.04
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser & Version
      placeholder: Chrome 131 / Safari 18.2 / Firefox 133 / In-app browser
    validations:
      required: true

  - type: dropdown
    id: wallet
    attributes:
      label: Wallet Used
      description: Which wallet was connected when the bug occurred?
      options:
        - MetaMask (browser extension)
        - MetaMask (mobile app)
        - Rabby
        - Coinbase Wallet
        - WalletConnect
        - Station (browser extension)
        - Station (mobile)
        - Keplr
        - Leap
        - Cosmostation
        - LuncDash (WalletConnect)
        - GalaxyStation (WalletConnect)
        - No wallet connected
        - Other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: network
    attributes:
      label: Network / Chain
      options:
        - BSC Mainnet
        - opBNB Mainnet
        - Terra Classic Mainnet
        - Local devnet
    validations:
      required: true

  - type: dropdown
    id: page
    attributes:
      label: Page Where Bug Occurred
      options:
        - Transfer (bridge form)
        - Transfer Status (pending/completed)
        - Hash Verification
        - Settings
        - History
        - Wallet Connect Modal
        - Navigation / Layout
        - Other
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Numbered steps to reliably reproduce the bug
      placeholder: |
        1. Open the app on [device]
        2. Connect [wallet]
        3. Navigate to [page]
        4. Do [action]
        5. Observe [bug]
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical (funds at risk, app crash, unusable)
        - High (core flow broken, bad UX on common path)
        - Medium (annoying but workaround exists)
        - Low (cosmetic, minor polish)
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recordings
      description: Paste screenshots or link to recordings. For mobile, a screen recording is very helpful.

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any errors from browser dev tools (if accessible)
      render: shell

  - type: input
    id: tx-hash
    attributes:
      label: Transaction Hash (if applicable)
      description: The on-chain tx hash if the bug involved a transaction
      placeholder: "0x..."

  - type: checkboxes
    id: source
    attributes:
      label: Bug Source
      options:
        - label: Found during manual QA testing
        - label: Reported by a user (escalated bug report)
