name: QA Test Pass
description: Record a manual test pass across devices, wallets, and flows
labels: ["qa", "test-pass"]
body:
  - type: input
    id: build
    attributes:
      label: Build / Commit Tested
      description: Git commit SHA or deployment URL tested
      placeholder: "abc1234 or https://cl8y-bridge.onrender.com"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date of Test Pass
      placeholder: "2026-03-01"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Wallet Connection
        Test connecting and disconnecting each wallet. Mark pass/fail/skip.

  - type: checkboxes
    id: evm-wallets
    attributes:
      label: "EVM Wallets"
      options:
        - label: "MetaMask (extension) — connect, disconnect, switch chain"
        - label: "MetaMask (mobile) — connect via in-app browser"
        - label: "Rabby — connect, disconnect"
        - label: "Coinbase Wallet — connect, disconnect"
        - label: "WalletConnect — connect, disconnect, QR scan"

  - type: checkboxes
    id: terra-wallets
    attributes:
      label: "Terra Wallets"
      options:
        - label: "Station (extension) — connect, disconnect"
        - label: "Station (mobile) — connect via WalletConnect"
        - label: "Keplr — connect, disconnect"
        - label: "Leap — connect, disconnect"
        - label: "Cosmostation — connect, disconnect"
        - label: "LuncDash — connect via WalletConnect"
        - label: "GalaxyStation — connect via WalletConnect"

  - type: markdown
    attributes:
      value: |
        ## Bridge Transfer Flows
        Test the core bridge flows end-to-end.

  - type: checkboxes
    id: bridge-flows
    attributes:
      label: "Transfer Flows"
      options:
        - label: "EVM → Terra Classic: initiate, sign, monitor status, complete"
        - label: "Terra Classic → EVM: initiate, sign, monitor status, complete"
        - label: "Transfer form validation (invalid amounts, empty fields, insufficient balance)"
        - label: "Fee breakdown displays correctly"
        - label: "Recipient address auto-fill from connected wallet"
        - label: "Manual recipient address entry"
        - label: "Token selection works for all registered tokens"
        - label: "Chain selection / swap direction button"

  - type: checkboxes
    id: status-flows
    attributes:
      label: "Transfer Status & History"
      options:
        - label: "Transfer status page updates in real-time"
        - label: "Auto-submit withdrawal works when wallet connected"
        - label: "Manual withdrawal flow works"
        - label: "History page shows past transfers"
        - label: "Transfer status badge states (pending, completed, failed)"

  - type: checkboxes
    id: verification-flows
    attributes:
      label: "Hash Verification"
      options:
        - label: "Hash search bar accepts valid tx hashes"
        - label: "Source and destination hash cards display correctly"
        - label: "Hash comparison panel shows match/mismatch"
        - label: "Fraud alert displays when hashes don't match"
        - label: "Recent verifications list works"

  - type: checkboxes
    id: settings-flows
    attributes:
      label: "Settings & Faucet"
      options:
        - label: "Chain connection status indicators work"
        - label: "Token list displays correctly"
        - label: "Bridge config panel shows correct values"
        - label: "Faucet claim works (mainnet test tokens)"

  - type: markdown
    attributes:
      value: |
        ## Device & Responsive Testing

  - type: checkboxes
    id: responsive
    attributes:
      label: "Responsive / Mobile"
      options:
        - label: "Layout renders correctly on small screens (< 375px)"
        - label: "Layout renders correctly on medium screens (375-768px)"
        - label: "Layout renders correctly on tablets (768-1024px)"
        - label: "Navigation bar is usable on mobile"
        - label: "Modals (wallet connect) are usable on mobile"
        - label: "Transfer form is usable on mobile (inputs, buttons, dropdowns)"
        - label: "No horizontal scroll on any page"
        - label: "Touch targets are large enough (min 44x44px)"

  - type: textarea
    id: devices-tested
    attributes:
      label: Devices Tested
      description: List every device/browser combination tested in this pass
      placeholder: |
        - iPhone 15 Pro / Safari 18.2
        - Samsung Galaxy S24 / Chrome 131
        - Pixel 8 / Firefox 133
        - MacBook Pro / Chrome 131
    validations:
      required: true

  - type: textarea
    id: bugs-found
    attributes:
      label: Bugs Found
      description: List any bugs discovered, with links to filed issues
      placeholder: |
        - #42 — Transfer button unresponsive on MetaMask mobile
        - #43 — Fee breakdown overlaps on small screens

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any observations, regressions, or areas needing deeper testing
