#!/usr/bin/env bash
# Merge scripts/qa/qa-host.env + .deploy/local.env into:
#   - .env.e2e.local (bash, for canceler / status / tooling)
#   - packages/frontend/.env.local (Vite, no "export" prefix)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

if [ ! -f "$REPO_ROOT/.deploy/local.env" ]; then
  echo "[write-qa-env-e2e] Missing .deploy/local.env — run make deploy first." >&2
  exit 1
fi

set -a
# shellcheck source=/dev/null
source "$REPO_ROOT/scripts/qa/qa-host.env"
# shellcheck source=/dev/null
source "$REPO_ROOT/.deploy/local.env"
set +a

E2E_OUT="$REPO_ROOT/.env.e2e.local"
FE_OUT="$REPO_ROOT/packages/frontend/.env.local"

{
  echo "# Generated by scripts/qa/write-qa-env-e2e.sh — do not commit"
  echo "export VITE_NETWORK=local"
  echo "export VITE_EVM_BRIDGE_ADDRESS=${EVM_BRIDGE_ADDRESS:-}"
  echo "export VITE_TERRA_BRIDGE_ADDRESS=${TERRA_BRIDGE_ADDRESS:-}"
  echo "export VITE_SOLANA_PROGRAM_ID=${SOLANA_PROGRAM_ID:-}"
  echo "export VITE_SOLANA_RPC_URL=${SOLANA_RPC_URL}"
  echo "export VITE_EVM_RPC_URL=${EVM_RPC_URL}"
  echo "export VITE_TERRA_LCD_URL=${TERRA_LCD_URL}"
  echo "export VITE_TERRA_RPC_URL=${TERRA_RPC_URL}"
  echo "export TERRA_RPC_URL=${TERRA_RPC_URL}"
  echo "export TERRA_LCD_URL=${TERRA_LCD_URL}"
  echo "export EVM_RPC_URL=${EVM_RPC_URL}"
  echo "export OPERATOR_API_URL=${OPERATOR_API_URL}"
  echo "export EVM_BRIDGE_ADDRESS=${EVM_BRIDGE_ADDRESS:-}"
  echo "export TERRA_BRIDGE_ADDRESS=${TERRA_BRIDGE_ADDRESS:-}"
  echo "export SOLANA_PROGRAM_ID=${SOLANA_PROGRAM_ID:-}"
} >"$E2E_OUT"

mkdir -p "$(dirname "$FE_OUT")"
{
  echo "# Generated by scripts/qa/write-qa-env-e2e.sh — do not commit"
  echo "VITE_NETWORK=local"
  echo "VITE_EVM_BRIDGE_ADDRESS=${EVM_BRIDGE_ADDRESS:-}"
  echo "VITE_TERRA_BRIDGE_ADDRESS=${TERRA_BRIDGE_ADDRESS:-}"
  echo "VITE_SOLANA_PROGRAM_ID=${SOLANA_PROGRAM_ID:-}"
  echo "VITE_SOLANA_RPC_URL=${SOLANA_RPC_URL}"
  echo "VITE_EVM_RPC_URL=${EVM_RPC_URL}"
  echo "VITE_TERRA_LCD_URL=${TERRA_LCD_URL}"
  echo "VITE_TERRA_RPC_URL=${TERRA_RPC_URL}"
} >"$FE_OUT"

echo "[write-qa-env-e2e] Wrote $E2E_OUT"
echo "[write-qa-env-e2e] Wrote $FE_OUT"
