#!/usr/bin/env bash
# Write packages/frontend/.env.local for local Vite dev against SSH port-forwards.
#
# URLs come from scripts/qa/qa-host.env (127.0.0.1 + same ports as make start-qa / docker compose).
# Contract addresses come from .deploy/local.env (same file make deploy writes on the QA host).
#
# Usage (laptop, after git clone):
#   scp user@qa-host:/path/to/cl8y-bridge-monorepo/.deploy/local.env .deploy/local.env
#   ./scripts/qa/write-frontend-env-local.sh
#   cd packages/frontend && npm run dev
#
# Or: npm run env:local --prefix packages/frontend
#
# Invoked by scripts/qa/write-qa-env-e2e.sh when run on the server after deploy.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_ENV="${REPO_ROOT}/.deploy/local.env"

if [ ! -f "$DEPLOY_ENV" ]; then
  echo "[write-frontend-env-local] Missing ${DEPLOY_ENV}" >&2
  echo "  After deploy on the QA host, copy that one file here, e.g.:" >&2
  echo "    mkdir -p .deploy && scp USER@QA_HOST:/srv/qa/repos/cl8y-bridge-monorepo/.deploy/local.env .deploy/local.env" >&2
  echo "  Then re-run this script." >&2
  exit 1
fi

# Match shared-host QA URLs (remapped Terra ports) so laptop + SSH -L match server loopback.
export QA_SHARED_HOST="${QA_SHARED_HOST:-1}"
set -a
# shellcheck source=/dev/null
source "${REPO_ROOT}/scripts/qa/qa-host.env"
# shellcheck source=/dev/null
source "$DEPLOY_ENV"
set +a

FE_OUT="${REPO_ROOT}/packages/frontend/.env.local"
mkdir -p "$(dirname "$FE_OUT")"

{
  echo "# Generated by scripts/qa/write-frontend-env-local.sh — do not commit"
  echo "VITE_NETWORK=local"
  echo "VITE_EVM_BRIDGE_ADDRESS=${EVM_BRIDGE_ADDRESS:-}"
  echo "VITE_TERRA_BRIDGE_ADDRESS=${TERRA_BRIDGE_ADDRESS:-}"
  echo "VITE_SOLANA_PROGRAM_ID=${SOLANA_PROGRAM_ID:-}"
  echo "VITE_SOLANA_RPC_URL=${SOLANA_RPC_URL}"
  echo "VITE_EVM_RPC_URL=${EVM_RPC_URL}"
  echo "VITE_TERRA_LCD_URL=${TERRA_LCD_URL}"
  echo "VITE_TERRA_RPC_URL=${TERRA_RPC_URL}"
} >"$FE_OUT"

echo "[write-frontend-env-local] Wrote ${FE_OUT}"
echo "[write-frontend-env-local] With SSH port forwards, these 127.0.0.1 URLs reach the QA host."
