#!/usr/bin/env bash
# Write packages/frontend/.env.local for local Vite dev against SSH port-forwards.
#
# URLs come from scripts/qa/qa-host.env (127.0.0.1 + same ports as make start-qa / docker compose).
# Contract addresses come from .deploy/local.env (same file make deploy writes on the QA host).
#
# Usage (laptop, after git clone):
#   scp user@qa-host:/path/to/cl8y-bridge-monorepo/.deploy/local.env .deploy/local.env
#   ./scripts/qa/write-frontend-env-local.sh
#   cd packages/frontend && npm run dev
#
# Or: npm run env:local --prefix packages/frontend
#
# Invoked by scripts/qa/write-qa-env-e2e.sh when run on the server after deploy.
#
# Optional: ./scripts/qa/write-frontend-env-local.sh --urls-only
#   If .deploy/local.env is missing, writes only VITE_* RPC/LCD URLs from qa-host.env (bridge addresses empty).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_ENV="${REPO_ROOT}/.deploy/local.env"

URLS_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --urls-only) URLS_ONLY=1 ;;
    -h|--help)
      echo "Usage: ${0##*/} [--urls-only]"
      echo "  Writes packages/frontend/.env.local from qa-host.env + (optional) .deploy/local.env"
      echo "  --urls-only  allow missing .deploy/local.env; URLs only, bridge address vars empty"
      exit 0
      ;;
  esac
done

if [ ! -f "$DEPLOY_ENV" ]; then
  if [ "$URLS_ONLY" != "1" ]; then
    echo "[write-frontend-env-local] Missing ${DEPLOY_ENV}" >&2
    echo "  Copy it from the QA host after deploy, then re-run. Example:" >&2
    echo "    mkdir -p .deploy && scp USER@HOST:/path/to/cl8y-bridge-monorepo/.deploy/local.env .deploy/local.env" >&2
    echo "  Or generate only RPC/LCD URLs (no bridge addresses) for tunnel / Settings checks:" >&2
    echo "    $0 --urls-only" >&2
    exit 1
  fi
  echo "[write-frontend-env-local] No ${DEPLOY_ENV} — writing VITE_* URLs only (--urls-only); bridge addresses will be empty." >&2
fi

# Match shared-host QA URLs (remapped Terra ports) so laptop + SSH -L match server loopback.
# Source deploy env *before* qa-host.env: .deploy/local.env may contain TERRA_LCD_URL / TERRA_RPC_URL
# from older tooling (e.g. localhost:1317) and would otherwise overwrite remapped ports (1318/26658).
export QA_SHARED_HOST="${QA_SHARED_HOST:-1}"
set -a
if [ -f "$DEPLOY_ENV" ]; then
  # shellcheck source=/dev/null
  source "$DEPLOY_ENV"
fi
# shellcheck source=/dev/null
source "${REPO_ROOT}/scripts/qa/qa-host.env"
set +a

FE_OUT="${REPO_ROOT}/packages/frontend/.env.local"
mkdir -p "$(dirname "$FE_OUT")"

{
  echo "# Generated by scripts/qa/write-frontend-env-local.sh — do not commit"
  echo "VITE_NETWORK=local"
  echo "VITE_EVM_BRIDGE_ADDRESS=${EVM_BRIDGE_ADDRESS:-}"
  echo "VITE_TERRA_BRIDGE_ADDRESS=${TERRA_BRIDGE_ADDRESS:-}"
  echo "VITE_SOLANA_PROGRAM_ID=${SOLANA_PROGRAM_ID:-}"
  echo "VITE_SOLANA_RPC_URL=${SOLANA_RPC_URL}"
  echo "VITE_EVM_RPC_URL=${EVM_RPC_URL}"
  echo "VITE_TERRA_LCD_URL=${TERRA_LCD_URL}"
  echo "VITE_TERRA_RPC_URL=${TERRA_RPC_URL}"
} >"$FE_OUT"

echo "[write-frontend-env-local] Wrote ${FE_OUT}"
echo "[write-frontend-env-local] Terra (must match SSH -L and Settings): LCD=${TERRA_LCD_URL:-?} RPC=${TERRA_RPC_URL:-?}"
echo "[write-frontend-env-local] With SSH port forwards, these 127.0.0.1 URLs reach the QA host."
