#!/usr/bin/env bash
# Write packages/frontend/.env.local for local Vite dev against SSH port-forwards.
#
# URLs come from scripts/qa/qa-host.env (127.0.0.1 + same ports as make start-qa / docker compose).
# Contract addresses come from .deploy/local.env (same file make deploy writes on the QA host).
#
# Usage (laptop, after git clone):
#   scp user@qa-host:/path/to/cl8y-bridge-monorepo/.deploy/local.env .deploy/local.env
#   ./scripts/qa/write-frontend-env-local.sh
#   cd packages/frontend && npm run dev
#
# Or: npm run env:local --prefix packages/frontend
#
# Invoked by scripts/qa/write-qa-env-e2e.sh when run on the server after deploy.
#
# Optional: ./scripts/qa/write-frontend-env-local.sh --urls-only
#   If .deploy/local.env is missing, writes only VITE_* RPC/LCD URLs from qa-host.env (bridge addresses empty).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEPLOY_ENV="${REPO_ROOT}/.deploy/local.env"

URLS_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --urls-only) URLS_ONLY=1 ;;
    -h|--help)
      echo "Usage: ${0##*/} [--urls-only]"
      echo "  Writes packages/frontend/.env.local from qa-host.env + (optional) .deploy/local.env"
      echo "  --urls-only  allow missing .deploy/local.env; URLs only, bridge address vars empty"
      exit 0
      ;;
  esac
done

if [ ! -f "$DEPLOY_ENV" ]; then
  if [ "$URLS_ONLY" != "1" ]; then
    echo "[write-frontend-env-local] Missing ${DEPLOY_ENV}" >&2
    echo "  Copy it from the QA host after deploy, then re-run. Example:" >&2
    echo "    scp USER@HOST:/path/to/cl8y-bridge-monorepo/.deploy/local.env .deploy/local.env" >&2
    echo "    (.deploy/ exists in the repo via .deploy/.gitkeep; mkdir -p .deploy only if your clone is old.)" >&2
    echo "  Or generate only RPC/LCD URLs (no bridge addresses) for tunnel / Settings checks:" >&2
    echo "    $0 --urls-only" >&2
    exit 1
  fi
  echo "[write-frontend-env-local] No ${DEPLOY_ENV} — writing VITE_* URLs only (--urls-only); bridge addresses will be empty." >&2
fi

# Source deploy env *before* qa-host.env: .deploy/local.env may set TERRA_LCD_URL / TERRA_RPC_URL;
# qa-host.env (and QA_SHARED_HOST) then aligns them with docker-compose publish ports.
export QA_SHARED_HOST="${QA_SHARED_HOST:-1}"
set -a
if [ -f "$DEPLOY_ENV" ]; then
  # Strip CRLF so sourcing works if the file was copied from Windows or via tee/SSH.
  # shellcheck source=/dev/null
  source <(sed 's/\r$//' "$DEPLOY_ENV")
fi
# shellcheck source=/dev/null
source "${REPO_ROOT}/scripts/qa/qa-host.env"
set +a

# If .deploy/local.env was copied before SOLANA_PROGRAM_ID was written (or line missing), derive from Anchor keypair.
_SOL_KP="${REPO_ROOT}/packages/contracts-solana/target/deploy/cl8y_bridge-keypair.json"
if [ -z "${SOLANA_PROGRAM_ID:-}" ] && [ -f "$_SOL_KP" ] && command -v solana-keygen >/dev/null 2>&1; then
  SOLANA_PROGRAM_ID="$(solana-keygen pubkey "$_SOL_KP" 2>/dev/null || true)"
  export SOLANA_PROGRAM_ID
  if [ -n "${SOLANA_PROGRAM_ID}" ]; then
    echo "[write-frontend-env-local] Derived SOLANA_PROGRAM_ID from ${_SOL_KP} (.deploy/local.env had none)" >&2
  fi
fi

FE_OUT="${REPO_ROOT}/packages/frontend/.env.local"
mkdir -p "$(dirname "$FE_OUT")"

{
  echo "# Generated by scripts/qa/write-frontend-env-local.sh — do not commit"
  echo "VITE_NETWORK=local"
  echo "VITE_EVM_BRIDGE_ADDRESS=${EVM_BRIDGE_ADDRESS:-}"
  echo "VITE_EVM1_BRIDGE_ADDRESS=${EVM1_BRIDGE_ADDRESS:-}"
  echo "VITE_EVM_ROUTER_ADDRESS=${EVM_ROUTER_ADDRESS:-${EVM_BRIDGE_ADDRESS:-}}"
  echo "VITE_LOCK_UNLOCK_ADDRESS=${LOCK_UNLOCK_ADDRESS:-}"
  echo "VITE_EVM1_LOCK_UNLOCK_ADDRESS=${EVM1_LOCK_UNLOCK_ADDRESS:-}"
  echo "VITE_BRIDGE_TOKEN_ADDRESS=${ANVIL_LUNC:-${TEST_TOKEN_ADDRESS:-}}"
  echo "VITE_TERRA_BRIDGE_ADDRESS=${TERRA_BRIDGE_ADDRESS:-}"
  echo "VITE_SOLANA_PROGRAM_ID=${SOLANA_PROGRAM_ID:-}"
  echo "VITE_SOLANA_RPC_URL=${SOLANA_RPC_URL}"
  echo "VITE_EVM_RPC_URL=${EVM_RPC_URL}"
  echo "VITE_EVM1_RPC_URL=${EVM1_RPC_URL}"
  echo "VITE_TERRA_LCD_URL=${TERRA_LCD_URL}"
  echo "VITE_TERRA_RPC_URL=${TERRA_RPC_URL}"
  echo "VITE_ANVIL_FAUCET_ADDRESS=${ANVIL_FAUCET_ADDRESS:-}"
  echo "VITE_ANVIL1_FAUCET_ADDRESS=${ANVIL1_FAUCET_ADDRESS:-}"
  echo "VITE_TERRA_FAUCET_ADDRESS=${TERRA_FAUCET_ADDRESS:-}"
  echo "VITE_SOLANA_FAUCET_ADDRESS=${SOLANA_FAUCET_PROGRAM_ID:-}"
  echo "VITE_ANVIL_TOKEN_A=${ANVIL_TOKEN_A:-}"
  echo "VITE_ANVIL_TOKEN_B=${ANVIL_TOKEN_B:-}"
  echo "VITE_ANVIL_TOKEN_C=${ANVIL_TOKEN_C:-}"
  echo "VITE_ANVIL_LUNC=${ANVIL_LUNC:-}"
  echo "VITE_ANVIL_KDEC=${ANVIL_KDEC:-}"
  echo "VITE_ANVIL_SOL=${ANVIL_SOL:-}"
  echo "VITE_ANVIL_T2022=${ANVIL_T2022:-}"
  echo "VITE_ANVIL1_TOKEN_A=${ANVIL1_TOKEN_A:-}"
  echo "VITE_ANVIL1_TOKEN_B=${ANVIL1_TOKEN_B:-}"
  echo "VITE_ANVIL1_TOKEN_C=${ANVIL1_TOKEN_C:-}"
  echo "VITE_ANVIL1_LUNC=${ANVIL1_LUNC:-}"
  echo "VITE_ANVIL1_KDEC=${ANVIL1_KDEC:-}"
  echo "VITE_ANVIL1_SOL=${ANVIL1_SOL:-}"
  echo "VITE_ANVIL1_T2022=${ANVIL1_T2022:-}"
  echo "VITE_TERRA_TOKEN_A=${TERRA_TOKEN_A:-}"
  echo "VITE_TERRA_TOKEN_B=${TERRA_TOKEN_B:-}"
  echo "VITE_TERRA_TOKEN_C=${TERRA_TOKEN_C:-}"
  echo "VITE_TERRA_KDEC=${TERRA_KDEC:-}"
  echo "VITE_TERRA_SOL=${TERRA_SOL:-}"
  echo "VITE_TERRA_T2022=${TERRA_T2022:-}"
  echo "VITE_SOLANA_TOKEN_A=${SOLANA_TOKEN_A:-}"
  echo "VITE_SOLANA_TOKEN_B=${SOLANA_TOKEN_B:-}"
  echo "VITE_SOLANA_TOKEN_C=${SOLANA_TOKEN_C:-}"
  echo "VITE_SOLANA_LUNC=${SOLANA_LUNC:-}"
  echo "VITE_SOLANA_KDEC=${SOLANA_KDEC:-}"
  echo "VITE_SOLANA_WSOL=${SOLANA_WSOL:-}"
  echo "VITE_SOLANA_T2022=${SOLANA_T2022:-}"
} >"$FE_OUT"

echo "[write-frontend-env-local] Wrote ${FE_OUT}"
echo "[write-frontend-env-local] Terra (must match SSH -L and Settings): LCD=${TERRA_LCD_URL:-?} RPC=${TERRA_RPC_URL:-?}"
echo "[write-frontend-env-local] With SSH port forwards, these 127.0.0.1 URLs reach the QA host."
