#!/usr/bin/env bash
# Merge scripts/qa/qa-host.env + .deploy/local.env into:
#   - .env.e2e.local (bash, for canceler / status / tooling)
#   - packages/frontend/.env.local (Vite, no "export" prefix)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

if [ ! -f "$REPO_ROOT/.deploy/local.env" ]; then
  echo "[write-qa-env-e2e] Missing .deploy/local.env — run make deploy first." >&2
  exit 1
fi

# Same order as write-frontend-env-local.sh: deploy first, then qa-host (remapped Terra URLs win).
export QA_SHARED_HOST="${QA_SHARED_HOST:-1}"
set -a
# shellcheck source=/dev/null
source "$REPO_ROOT/.deploy/local.env"
# shellcheck source=/dev/null
source "$REPO_ROOT/scripts/qa/qa-host.env"
set +a

E2E_OUT="$REPO_ROOT/.env.e2e.local"

{
  echo "# Generated by scripts/qa/write-qa-env-e2e.sh — do not commit"
  echo "export VITE_NETWORK=local"
  echo "export VITE_EVM_BRIDGE_ADDRESS=${EVM_BRIDGE_ADDRESS:-}"
  echo "export VITE_EVM1_BRIDGE_ADDRESS=${EVM1_BRIDGE_ADDRESS:-}"
  echo "export VITE_EVM_ROUTER_ADDRESS=${EVM_ROUTER_ADDRESS:-${EVM_BRIDGE_ADDRESS:-}}"
  echo "export VITE_LOCK_UNLOCK_ADDRESS=${LOCK_UNLOCK_ADDRESS:-}"
  echo "export VITE_EVM1_LOCK_UNLOCK_ADDRESS=${EVM1_LOCK_UNLOCK_ADDRESS:-}"
  echo "export VITE_BRIDGE_TOKEN_ADDRESS=${ANVIL_LUNC:-${TEST_TOKEN_ADDRESS:-}}"
  echo "export VITE_TERRA_BRIDGE_ADDRESS=${TERRA_BRIDGE_ADDRESS:-}"
  echo "export VITE_SOLANA_PROGRAM_ID=${SOLANA_PROGRAM_ID:-}"
  echo "export VITE_SOLANA_RPC_URL=${SOLANA_RPC_URL}"
  echo "export VITE_EVM_RPC_URL=${EVM_RPC_URL}"
  echo "export VITE_EVM1_RPC_URL=${EVM1_RPC_URL}"
  echo "export VITE_TERRA_LCD_URL=${TERRA_LCD_URL}"
  echo "export VITE_TERRA_RPC_URL=${TERRA_RPC_URL}"
  echo "export VITE_ANVIL_FAUCET_ADDRESS=${ANVIL_FAUCET_ADDRESS:-}"
  echo "export VITE_ANVIL1_FAUCET_ADDRESS=${ANVIL1_FAUCET_ADDRESS:-}"
  echo "export VITE_TERRA_FAUCET_ADDRESS=${TERRA_FAUCET_ADDRESS:-}"
  echo "export VITE_SOLANA_FAUCET_ADDRESS=${SOLANA_FAUCET_PROGRAM_ID:-}"
  echo "export VITE_ANVIL_TOKEN_A=${ANVIL_TOKEN_A:-}"
  echo "export VITE_ANVIL_TOKEN_B=${ANVIL_TOKEN_B:-}"
  echo "export VITE_ANVIL_TOKEN_C=${ANVIL_TOKEN_C:-}"
  echo "export VITE_ANVIL_LUNC=${ANVIL_LUNC:-}"
  echo "export VITE_ANVIL_KDEC=${ANVIL_KDEC:-}"
  echo "export VITE_ANVIL_SOL=${ANVIL_SOL:-}"
  echo "export VITE_ANVIL1_TOKEN_A=${ANVIL1_TOKEN_A:-}"
  echo "export VITE_ANVIL1_TOKEN_B=${ANVIL1_TOKEN_B:-}"
  echo "export VITE_ANVIL1_TOKEN_C=${ANVIL1_TOKEN_C:-}"
  echo "export VITE_ANVIL1_LUNC=${ANVIL1_LUNC:-}"
  echo "export VITE_ANVIL1_KDEC=${ANVIL1_KDEC:-}"
  echo "export VITE_ANVIL1_SOL=${ANVIL1_SOL:-}"
  echo "export VITE_TERRA_TOKEN_A=${TERRA_TOKEN_A:-}"
  echo "export VITE_TERRA_TOKEN_B=${TERRA_TOKEN_B:-}"
  echo "export VITE_TERRA_TOKEN_C=${TERRA_TOKEN_C:-}"
  echo "export VITE_TERRA_KDEC=${TERRA_KDEC:-}"
  echo "export VITE_TERRA_SOL=${TERRA_SOL:-}"
  echo "export VITE_SOLANA_TOKEN_A=${SOLANA_TOKEN_A:-}"
  echo "export VITE_SOLANA_TOKEN_B=${SOLANA_TOKEN_B:-}"
  echo "export VITE_SOLANA_TOKEN_C=${SOLANA_TOKEN_C:-}"
  echo "export VITE_SOLANA_LUNC=${SOLANA_LUNC:-}"
  echo "export VITE_SOLANA_KDEC=${SOLANA_KDEC:-}"
  echo "export VITE_SOLANA_WSOL=${SOLANA_WSOL:-}"
  echo "export TERRA_RPC_URL=${TERRA_RPC_URL}"
  echo "export TERRA_LCD_URL=${TERRA_LCD_URL}"
  echo "export EVM_RPC_URL=${EVM_RPC_URL}"
  echo "export EVM1_RPC_URL=${EVM1_RPC_URL}"
  echo "export OPERATOR_API_URL=${OPERATOR_API_URL}"
  echo "export EVM_BRIDGE_ADDRESS=${EVM_BRIDGE_ADDRESS:-}"
  echo "export EVM1_BRIDGE_ADDRESS=${EVM1_BRIDGE_ADDRESS:-}"
  echo "export EVM1_LOCK_UNLOCK_ADDRESS=${EVM1_LOCK_UNLOCK_ADDRESS:-}"
  echo "export TERRA_BRIDGE_ADDRESS=${TERRA_BRIDGE_ADDRESS:-}"
  echo "export SOLANA_PROGRAM_ID=${SOLANA_PROGRAM_ID:-}"
} >"$E2E_OUT"

chmod +x "$REPO_ROOT/scripts/qa/write-frontend-env-local.sh" 2>/dev/null || true
"$REPO_ROOT/scripts/qa/write-frontend-env-local.sh"

echo "[write-qa-env-e2e] Wrote $E2E_OUT"
echo "[write-qa-env-e2e] Frontend env via write-frontend-env-local.sh → packages/frontend/.env.local"
