[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cl8y_bridge = "CL8YBr1dg3So1ana111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
