#!/usr/bin/env bash
# Shared helpers for .deploy/local.env (EVM + Terra bridge addresses for local make deploy).
# shellcheck shell=bash

_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$_LIB_DIR/.." && pwd)"
DEPLOY_ENV_FILE="${REPO_ROOT}/.deploy/local.env"

# Lines to preserve when rewriting primary EVM (second anvil, Terra, Solana, tokens).
_preserve_non_primary_evm_lines() {
    [ ! -f "$DEPLOY_ENV_FILE" ] && return 0
    grep -E '^export (EVM1_|SOLANA_PROGRAM_ID|TERRA_|TEST_TOKEN_ADDRESS|TERRA_CW20)' "$DEPLOY_ENV_FILE" 2>/dev/null || true
}

write_deploy_env_evm() {
    local bridge=$1
    local cr=${2:-}
    local tr=${3:-}
    local lu=${4:-}
    mkdir -p "$(dirname "$DEPLOY_ENV_FILE")"
    local preserved
    preserved="$(_preserve_non_primary_evm_lines)"
    {
        echo "# Generated by deploy-evm / deploy-terra (make deploy). Not committed."
        echo "export EVM_BRIDGE_ADDRESS=$bridge"
        echo "export EVM_CHAIN_REGISTRY=$cr"
        [ -n "$tr" ] && echo "export TOKEN_REGISTRY_ADDRESS=$tr"
        [ -n "$lu" ] && echo "export LOCK_UNLOCK_ADDRESS=$lu"
        if [ -n "$preserved" ]; then
            echo "$preserved"
        fi
    } >"$DEPLOY_ENV_FILE"
}

# Merge second Anvil (anvil1) deploy output into .deploy/local.env without clobbering primary EVM / Terra / Solana.
write_deploy_env_evm1() {
    local bridge=$1
    local cr=${2:-}
    local tr=${3:-}
    local lu=${4:-}
    mkdir -p "$(dirname "$DEPLOY_ENV_FILE")"
    local tmp
    tmp=$(mktemp)
    if [ -f "$DEPLOY_ENV_FILE" ]; then
        grep -vE '^export EVM1_(BRIDGE_ADDRESS|CHAIN_REGISTRY|TOKEN_REGISTRY_ADDRESS|LOCK_UNLOCK_ADDRESS)=' "$DEPLOY_ENV_FILE" >"$tmp" || true
    else
        echo "# Generated by deploy-evm1 (make deploy). Not committed." >"$tmp"
    fi
    {
        echo "export EVM1_BRIDGE_ADDRESS=$bridge"
        [ -n "$cr" ] && echo "export EVM1_CHAIN_REGISTRY=$cr"
        [ -n "$tr" ] && echo "export EVM1_TOKEN_REGISTRY_ADDRESS=$tr"
        [ -n "$lu" ] && echo "export EVM1_LOCK_UNLOCK_ADDRESS=$lu"
    } >>"$tmp"
    mv "$tmp" "$DEPLOY_ENV_FILE"
}

write_deploy_env_terra() {
    local tb=$1
    local cw20=${2:-}
    mkdir -p "$(dirname "$DEPLOY_ENV_FILE")"
    local evm_b="" evm_cr="" tr_l="" lu_l="" tt_l="" cw20_prev="" evm1_lines="" sol_id=""
    if [ -f "$DEPLOY_ENV_FILE" ]; then
        evm_b=$(grep '^export EVM_BRIDGE_ADDRESS=' "$DEPLOY_ENV_FILE" | sed 's/^export EVM_BRIDGE_ADDRESS=//' | tr -d '\r' || true)
        evm_cr=$(grep '^export EVM_CHAIN_REGISTRY=' "$DEPLOY_ENV_FILE" | sed 's/^export EVM_CHAIN_REGISTRY=//' | tr -d '\r' || true)
        tr_l=$(grep '^export TOKEN_REGISTRY_ADDRESS=' "$DEPLOY_ENV_FILE" || true)
        lu_l=$(grep '^export LOCK_UNLOCK_ADDRESS=' "$DEPLOY_ENV_FILE" || true)
        tt_l=$(grep '^export TEST_TOKEN_ADDRESS=' "$DEPLOY_ENV_FILE" || true)
        cw20_prev=$(grep '^export TERRA_CW20_ADDRESS=' "$DEPLOY_ENV_FILE" || true)
        evm1_lines=$(grep -E '^export EVM1_' "$DEPLOY_ENV_FILE" || true)
        sol_id=$(grep '^export SOLANA_PROGRAM_ID=' "$DEPLOY_ENV_FILE" || true)
    fi
    {
        echo "# Generated by deploy-evm / deploy-terra (make deploy). Not committed."
        [ -n "$evm_b" ] && echo "export EVM_BRIDGE_ADDRESS=$evm_b"
        [ -n "$evm_cr" ] && echo "export EVM_CHAIN_REGISTRY=$evm_cr"
        [ -n "$tr_l" ] && echo "$tr_l"
        [ -n "$lu_l" ] && echo "$lu_l"
        [ -n "$tt_l" ] && echo "$tt_l"
        if [ -n "$evm1_lines" ]; then
            echo "$evm1_lines"
        fi
        [ -n "$sol_id" ] && echo "$sol_id"
        echo "export TERRA_BRIDGE_ADDRESS=$tb"
        if [ -n "$cw20" ]; then
            echo "export TERRA_CW20_ADDRESS=$cw20"
        elif [ -n "$cw20_prev" ]; then
            echo "$cw20_prev"
        fi
    } >"$DEPLOY_ENV_FILE"
}

write_deploy_env_solana() {
    local pid=$1
    mkdir -p "$(dirname "$DEPLOY_ENV_FILE")"
    local tmp="${DEPLOY_ENV_FILE}.tmp"
    if [ -f "$DEPLOY_ENV_FILE" ]; then
        grep -v '^export SOLANA_PROGRAM_ID=' "$DEPLOY_ENV_FILE" > "$tmp" || true
    else
        echo "# Generated by deploy-evm / deploy-terra / deploy-solana (make deploy). Not committed." > "$tmp"
    fi
    echo "export SOLANA_PROGRAM_ID=$pid" >> "$tmp"
    mv "$tmp" "$DEPLOY_ENV_FILE"
}

load_local_deploy_env() {
    local f="$DEPLOY_ENV_FILE"
    [ ! -f "$f" ] && return 0
    # Use mapfile instead of `while read || [ -n "$line" ]` — the EOF `[ -n "$line" ]` test
    # returns 1 and can trigger bash ERR traps (set -E) even though the while is exiting normally.
    local lines
    mapfile -t lines <"$f" || return 0
    local line
    for line in "${lines[@]}"; do
        [[ "$line" =~ ^# ]] && continue
        [[ -z "$line" ]] && continue
        key="${line#export }"
        key="${key%%=*}"
        val="${line#*=}"
        case "$key" in
        EVM_BRIDGE_ADDRESS)
            if [ -z "${EVM_BRIDGE_ADDRESS:-}" ]; then export EVM_BRIDGE_ADDRESS="$val"; fi
            ;;
        EVM_CHAIN_REGISTRY)
            if [ -z "${EVM_CHAIN_REGISTRY:-}" ]; then export EVM_CHAIN_REGISTRY="$val"; fi
            ;;
        TERRA_BRIDGE_ADDRESS)
            if [ -z "${TERRA_BRIDGE_ADDRESS:-}" ]; then export TERRA_BRIDGE_ADDRESS="$val"; fi
            ;;
        SOLANA_PROGRAM_ID)
            if [ -z "${SOLANA_PROGRAM_ID:-}" ]; then export SOLANA_PROGRAM_ID="$val"; fi
            ;;
        TOKEN_REGISTRY_ADDRESS)
            if [ -z "${TOKEN_REGISTRY_ADDRESS:-}" ]; then export TOKEN_REGISTRY_ADDRESS="$val"; fi
            ;;
        LOCK_UNLOCK_ADDRESS)
            if [ -z "${LOCK_UNLOCK_ADDRESS:-}" ]; then export LOCK_UNLOCK_ADDRESS="$val"; fi
            ;;
        MINT_BURN_ADDRESS)
            if [ -z "${MINT_BURN_ADDRESS:-}" ]; then export MINT_BURN_ADDRESS="$val"; fi
            ;;
        TEST_TOKEN_ADDRESS)
            if [ -z "${TEST_TOKEN_ADDRESS:-}" ]; then export TEST_TOKEN_ADDRESS="$val"; fi
            ;;
        TERRA_CW20_ADDRESS)
            if [ -z "${TERRA_CW20_ADDRESS:-}" ]; then export TERRA_CW20_ADDRESS="$val"; fi
            ;;
        EVM1_BRIDGE_ADDRESS)
            if [ -z "${EVM1_BRIDGE_ADDRESS:-}" ]; then export EVM1_BRIDGE_ADDRESS="$val"; fi
            ;;
        EVM1_CHAIN_REGISTRY)
            if [ -z "${EVM1_CHAIN_REGISTRY:-}" ]; then export EVM1_CHAIN_REGISTRY="$val"; fi
            ;;
        EVM1_TOKEN_REGISTRY_ADDRESS)
            if [ -z "${EVM1_TOKEN_REGISTRY_ADDRESS:-}" ]; then export EVM1_TOKEN_REGISTRY_ADDRESS="$val"; fi
            ;;
        EVM1_LOCK_UNLOCK_ADDRESS)
            if [ -z "${EVM1_LOCK_UNLOCK_ADDRESS:-}" ]; then export EVM1_LOCK_UNLOCK_ADDRESS="$val"; fi
            ;;
        esac
    done
}

# Console hints for QA when local deploy env is missing or broken (stderr).
qa_hint_env_file_path() {
    echo "" >&2
    echo "  Expected file: ${DEPLOY_ENV_FILE}" >&2
}

qa_hint_evm_bridge_missing() {
    echo "" >&2
    echo "=== QA: EVM bridge address is not set ===" >&2
    qa_hint_env_file_path
    echo "  1) Start Anvil and deploy EVM contracts, then re-run setup:" >&2
    echo "       make start" >&2
    echo "       make deploy-evm" >&2
    echo "     That writes EVM_BRIDGE_ADDRESS into the file above." >&2
    echo "  2) Or export it for this shell only, then run setup-bridge again:" >&2
    echo "       export EVM_BRIDGE_ADDRESS=0x...   # from forge script output (DEPLOYED_BRIDGE)" >&2
    echo "  3) Check Anvil is reachable: cast block-number --rpc-url http://localhost:8545" >&2
    echo "  4) Full local stack: make deploy   (runs deploy-evm, deploy-terra, deploy-solana, setup-bridge)" >&2
    echo "" >&2
}

qa_hint_terra_bridge_missing() {
    echo "" >&2
    echo "=== QA: Terra bridge address is not set ===" >&2
    qa_hint_env_file_path
    echo "  1) Ensure LocalTerra is up: docker compose up -d localterra   (or make start)" >&2
    echo "  2) Deploy the Terra bridge and refresh the env file:" >&2
    echo "       ./scripts/deploy-terra-local.sh" >&2
    echo "     That appends TERRA_BRIDGE_ADDRESS into the file above (keeps EVM lines)." >&2
    echo "  3) Or export manually from the script output (TERRA_BRIDGE_ADDRESS=terra1...):" >&2
    echo "       export TERRA_BRIDGE_ADDRESS=terra1..." >&2
    echo "  4) Run the full chain: make deploy" >&2
    echo "" >&2
}

qa_hint_localterra_not_running() {
    local name=$1
    echo "" >&2
    echo "=== QA: LocalTerra container is not running ===" >&2
    echo "  Expected container name: ${name}" >&2
    echo "  1) Start services: make start   or   docker compose up -d localterra" >&2
    echo "  2) Check: docker ps   and   make status" >&2
    echo "" >&2
}

qa_hint_forge_evm_deploy_failed() {
    local logf=$1
    echo "" >&2
    echo "=== QA: forge script (EVM deploy) failed ===" >&2
    echo "  1) Anvil must be running on http://localhost:8545:" >&2
    echo "       make start   or   docker compose up -d anvil" >&2
    echo "  2) Verify: cast block-number --rpc-url http://localhost:8545" >&2
    echo "  3) Re-run: make deploy-evm" >&2
    echo "  4) If forge still fails, see the log above. Last lines of captured output:" >&2
    if [ -n "$logf" ] && [ -f "$logf" ]; then
        tail -25 "$logf" >&2
    fi
    echo "" >&2
}

qa_hint_forge_evm1_deploy_failed() {
    local logf=$1
    echo "" >&2
    echo "=== QA: forge script (EVM anvil1 deploy) failed ===" >&2
    echo "  1) Second Anvil must be running (e.g. http://127.0.0.1:8546):" >&2
    echo "       docker compose up -d anvil1" >&2
    echo "  2) Verify: cast block-number --rpc-url \${EVM1_RPC_URL:-http://127.0.0.1:8546}" >&2
    echo "  3) Re-run: make deploy-evm1" >&2
    echo "  4) If forge still fails, see the log below." >&2
    if [ -n "$logf" ] && [ -f "$logf" ]; then
        tail -25 "$logf" >&2
    fi
    echo "" >&2
}

qa_hint_evm_log_parse_failed() {
    local logf=$1
    echo "" >&2
    echo "=== QA: Could not read DEPLOYED_BRIDGE from forge output ===" >&2
    echo "  The deploy may have succeeded but log format changed. Try:" >&2
    echo "  1) Find DEPLOYED_BRIDGE in the output above, then:" >&2
    echo "       export EVM_BRIDGE_ADDRESS=0x...   EVM_CHAIN_REGISTRY=0x..." >&2
    echo "       ./scripts/setup-bridge.sh" >&2
    echo "  2) Or inspect: packages/contracts-evm/broadcast/DeployLocal.s.sol/31337/run-latest.json" >&2
    echo "  3) Report this to maintainers with the tail of the log below." >&2
    if [ -n "$logf" ] && [ -f "$logf" ]; then
        echo "" >&2
        echo "--- tail of forge log ---" >&2
        tail -40 "$logf" >&2
    fi
    echo "" >&2
}
