#!/usr/bin/env bash
# Shared helpers for .deploy/local.env (EVM + Terra bridge addresses for local make deploy).
# shellcheck shell=bash

_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$_LIB_DIR/.." && pwd)"
DEPLOY_ENV_FILE="${REPO_ROOT}/.deploy/local.env"

write_deploy_env_evm() {
    local bridge=$1
    local cr=${2:-}
    mkdir -p "$(dirname "$DEPLOY_ENV_FILE")"
    local terra_line=""
    if [ -f "$DEPLOY_ENV_FILE" ]; then
        terra_line=$(grep '^export TERRA_BRIDGE_ADDRESS=' "$DEPLOY_ENV_FILE" || true)
    fi
    {
        echo "# Generated by deploy-evm / deploy-terra (make deploy). Not committed."
        echo "export EVM_BRIDGE_ADDRESS=$bridge"
        echo "export EVM_CHAIN_REGISTRY=$cr"
        if [ -n "$terra_line" ]; then
            echo "$terra_line"
        fi
    } >"$DEPLOY_ENV_FILE"
}

write_deploy_env_terra() {
    local tb=$1
    mkdir -p "$(dirname "$DEPLOY_ENV_FILE")"
    local evm_b="" evm_cr=""
    if [ -f "$DEPLOY_ENV_FILE" ]; then
        evm_b=$(grep '^export EVM_BRIDGE_ADDRESS=' "$DEPLOY_ENV_FILE" | sed 's/^export EVM_BRIDGE_ADDRESS=//' | tr -d '\r' || true)
        evm_cr=$(grep '^export EVM_CHAIN_REGISTRY=' "$DEPLOY_ENV_FILE" | sed 's/^export EVM_CHAIN_REGISTRY=//' | tr -d '\r' || true)
    fi
    {
        echo "# Generated by deploy-evm / deploy-terra (make deploy). Not committed."
        [ -n "$evm_b" ] && echo "export EVM_BRIDGE_ADDRESS=$evm_b"
        [ -n "$evm_cr" ] && echo "export EVM_CHAIN_REGISTRY=$evm_cr"
        echo "export TERRA_BRIDGE_ADDRESS=$tb"
    } >"$DEPLOY_ENV_FILE"
}

load_local_deploy_env() {
    local f="$DEPLOY_ENV_FILE"
    [ ! -f "$f" ] && return 0
    while IFS= read -r line || [ -n "$line" ]; do
        [[ "$line" =~ ^# ]] && continue
        [[ -z "$line" ]] && continue
        key="${line#export }"
        key="${key%%=*}"
        val="${line#*=}"
        case "$key" in
        EVM_BRIDGE_ADDRESS) [ -z "${EVM_BRIDGE_ADDRESS:-}" ] && export EVM_BRIDGE_ADDRESS="$val" ;;
        EVM_CHAIN_REGISTRY) [ -z "${EVM_CHAIN_REGISTRY:-}" ] && export EVM_CHAIN_REGISTRY="$val" ;;
        TERRA_BRIDGE_ADDRESS) [ -z "${TERRA_BRIDGE_ADDRESS:-}" ] && export TERRA_BRIDGE_ADDRESS="$val" ;;
        esac
    done <"$f"
}

# Console hints for QA when local deploy env is missing or broken (stderr).
qa_hint_env_file_path() {
    echo "" >&2
    echo "  Expected file: ${DEPLOY_ENV_FILE}" >&2
}

qa_hint_evm_bridge_missing() {
    echo "" >&2
    echo "=== QA: EVM bridge address is not set ===" >&2
    qa_hint_env_file_path
    echo "  1) Start Anvil and deploy EVM contracts, then re-run setup:" >&2
    echo "       make start" >&2
    echo "       make deploy-evm" >&2
    echo "     That writes EVM_BRIDGE_ADDRESS into the file above." >&2
    echo "  2) Or export it for this shell only, then run setup-bridge again:" >&2
    echo "       export EVM_BRIDGE_ADDRESS=0x...   # from forge script output (DEPLOYED_BRIDGE)" >&2
    echo "  3) Check Anvil is reachable: cast block-number --rpc-url http://localhost:8545" >&2
    echo "  4) Full local stack: make deploy   (runs deploy-evm, deploy-terra, deploy-solana, setup-bridge)" >&2
    echo "" >&2
}

qa_hint_terra_bridge_missing() {
    echo "" >&2
    echo "=== QA: Terra bridge address is not set ===" >&2
    qa_hint_env_file_path
    echo "  1) Ensure LocalTerra is up: docker compose up -d localterra   (or make start)" >&2
    echo "  2) Deploy the Terra bridge and refresh the env file:" >&2
    echo "       ./scripts/deploy-terra-local.sh" >&2
    echo "     That appends TERRA_BRIDGE_ADDRESS into the file above (keeps EVM lines)." >&2
    echo "  3) Or export manually from the script output (TERRA_BRIDGE_ADDRESS=terra1...):" >&2
    echo "       export TERRA_BRIDGE_ADDRESS=terra1..." >&2
    echo "  4) Run the full chain: make deploy" >&2
    echo "" >&2
}

qa_hint_localterra_not_running() {
    local name=$1
    echo "" >&2
    echo "=== QA: LocalTerra container is not running ===" >&2
    echo "  Expected container name: ${name}" >&2
    echo "  1) Start services: make start   or   docker compose up -d localterra" >&2
    echo "  2) Check: docker ps   and   make status" >&2
    echo "" >&2
}

qa_hint_forge_evm_deploy_failed() {
    local logf=$1
    echo "" >&2
    echo "=== QA: forge script (EVM deploy) failed ===" >&2
    echo "  1) Anvil must be running on http://localhost:8545:" >&2
    echo "       make start   or   docker compose up -d anvil" >&2
    echo "  2) Verify: cast block-number --rpc-url http://localhost:8545" >&2
    echo "  3) Re-run: make deploy-evm" >&2
    echo "  4) If forge still fails, see the log above. Last lines of captured output:" >&2
    if [ -n "$logf" ] && [ -f "$logf" ]; then
        tail -25 "$logf" >&2
    fi
    echo "" >&2
}

qa_hint_evm_log_parse_failed() {
    local logf=$1
    echo "" >&2
    echo "=== QA: Could not read DEPLOYED_BRIDGE from forge output ===" >&2
    echo "  The deploy may have succeeded but log format changed. Try:" >&2
    echo "  1) Find DEPLOYED_BRIDGE in the output above, then:" >&2
    echo "       export EVM_BRIDGE_ADDRESS=0x...   EVM_CHAIN_REGISTRY=0x..." >&2
    echo "       ./scripts/setup-bridge.sh" >&2
    echo "  2) Or inspect: packages/contracts-evm/broadcast/DeployLocal.s.sol/31337/run-latest.json" >&2
    echo "  3) Report this to maintainers with the tail of the log below." >&2
    if [ -n "$logf" ] && [ -f "$logf" ]; then
        echo "" >&2
        echo "--- tail of forge log ---" >&2
        tail -40 "$logf" >&2
    fi
    echo "" >&2
}
