#!/usr/bin/env bash
# Run DeployTestToken forge script and append TEST_TOKEN_ADDRESS to .deploy/local.env
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib-local-deploy-env.sh
source "$SCRIPT_DIR/lib-local-deploy-env.sh"

LOG=$(mktemp)
trap 'rm -f "$LOG"' EXIT

cd "$REPO_ROOT/packages/contracts-evm"
if ! forge script script/DeployTestToken.s.sol:DeployTestToken \
  --broadcast \
  --rpc-url http://localhost:8545 \
  2>&1 | tee "$LOG"; then
  echo "[record-test-token] forge deploy failed" >&2
  exit 1
fi

ADDR=""
if grep -q 'TEST_TOKEN_ADDRESS' "$LOG"; then
  ADDR=$(grep 'TEST_TOKEN_ADDRESS' "$LOG" | grep -oE '0x[a-fA-F0-9]{40}' | head -1 || true)
fi
if [ -z "$ADDR" ]; then
  ADDR=$(grep -i 'TestToken' "$LOG" | grep -oE '0x[a-fA-F0-9]{40}' | head -1 || true)
fi
if [ -z "$ADDR" ]; then
  echo "[record-test-token] Could not parse test token address from forge output" >&2
  exit 1
fi

mkdir -p "$(dirname "$DEPLOY_ENV_FILE")"
if [ ! -f "$DEPLOY_ENV_FILE" ]; then
  echo "# Generated by deploy scripts — not committed." >"$DEPLOY_ENV_FILE"
fi
tmp=$(mktemp)
grep -v '^export TEST_TOKEN_ADDRESS=' "$DEPLOY_ENV_FILE" >"$tmp" || true
echo "export TEST_TOKEN_ADDRESS=$ADDR" >>"$tmp"
mv "$tmp" "$DEPLOY_ENV_FILE"
echo "[record-test-token] export TEST_TOKEN_ADDRESS=$ADDR -> $DEPLOY_ENV_FILE"
